ALTER TABLE `user` ADD COLUMN `email` VARCHAR(300) NULL;
ALTER TABLE `user` ADD COLUMN `firstlogin` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `user` ADD COLUMN `lastlogin` DATETIME NULL;
ALTER TABLE `user` ADD COLUMN `guest` TINYINT(1) NOT NULL DEFAULT 0;
