/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpusSourcedocument extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1553063081;

	/**
	 * The singleton instance of <code>CatmaRepository.corpus_sourcedocument</code>
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument CORPUS_SOURCEDOCUMENT = new de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.corpus_sourcedocument.corpus_sourcedocumentID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CORPUS_SOURCEDOCUMENTID = createField("corpus_sourcedocumentID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.corpus_sourcedocument.corpusID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CORPUSID = createField("corpusID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.corpus_sourcedocument.sourceDocumentID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> SOURCEDOCUMENTID = createField("sourceDocumentID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>CatmaRepository.corpus_sourcedocument</code> table reference
	 */
	public CorpusSourcedocument() {
		super("corpus_sourcedocument", de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.corpus_sourcedocument</code> table reference
	 */
	public CorpusSourcedocument(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument.CORPUS_SOURCEDOCUMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooq.catmarepository.Keys.IDENTITY_CORPUS_SOURCEDOCUMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooq.catmarepository.Keys.KEY_CORPUS_SOURCEDOCUMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooq.catmarepository.Keys.KEY_CORPUS_SOURCEDOCUMENT_PRIMARY, de.catma.repository.db.jooq.catmarepository.Keys.KEY_CORPUS_SOURCEDOCUMENT_UK_CORPUSSD_CORPUSID_SDID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooq.catmarepository.Keys.FK_CORPUSSD_CORPUSID, de.catma.repository.db.jooq.catmarepository.Keys.FK_CORPUSSD_SOURCEDOCUMENTID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument as(java.lang.String alias) {
		return new de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument(alias);
	}
}
