/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Propertydefinition extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -2092410078;

	/**
	 * The singleton instance of <code>CatmaRepository.propertydefinition</code>
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition PROPERTYDEFINITION = new de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.propertydefinition.propertyDefinitionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> PROPERTYDEFINITIONID = createField("propertyDefinitionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.propertydefinition.uuid</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.BINARY.length(16), this);

	/**
	 * The column <code>CatmaRepository.propertydefinition.name</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>CatmaRepository.propertydefinition.tagDefinitionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TAGDEFINITIONID = createField("tagDefinitionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.propertydefinition.systemproperty</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> SYSTEMPROPERTY = createField("systemproperty", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * Create a <code>CatmaRepository.propertydefinition</code> table reference
	 */
	public Propertydefinition() {
		super("propertydefinition", de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.propertydefinition</code> table reference
	 */
	public Propertydefinition(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition.PROPERTYDEFINITION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooq.catmarepository.Keys.IDENTITY_PROPERTYDEFINITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooq.catmarepository.Keys.KEY_PROPERTYDEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooq.catmarepository.Keys.KEY_PROPERTYDEFINITION_PRIMARY, de.catma.repository.db.jooq.catmarepository.Keys.KEY_PROPERTYDEFINITION_UK_PD_UUID_TDEF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooq.catmarepository.Keys.FK_PD_TAGDEFINITIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition as(java.lang.String alias) {
		return new de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition(alias);
	}
}
