/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagdefinition extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -1733793883;

	/**
	 * The singleton instance of <code>CatmaRepository.tagdefinition</code>
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition TAGDEFINITION = new de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.tagdefinition.tagDefinitionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TAGDEFINITIONID = createField("tagDefinitionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.tagdefinition.uuid</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.BINARY.length(16), this);

	/**
	 * The column <code>CatmaRepository.tagdefinition.version</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> VERSION = createField("version", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>CatmaRepository.tagdefinition.name</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>CatmaRepository.tagdefinition.tagsetDefinitionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TAGSETDEFINITIONID = createField("tagsetDefinitionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.tagdefinition.parentID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> PARENTID = createField("parentID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.tagdefinition.parentUuid</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, byte[]> PARENTUUID = createField("parentUuid", org.jooq.impl.SQLDataType.BINARY.length(16), this);

	/**
	 * Create a <code>CatmaRepository.tagdefinition</code> table reference
	 */
	public Tagdefinition() {
		super("tagdefinition", de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.tagdefinition</code> table reference
	 */
	public Tagdefinition(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition.TAGDEFINITION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooq.catmarepository.Keys.IDENTITY_TAGDEFINITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooq.catmarepository.Keys.KEY_TAGDEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooq.catmarepository.Keys.KEY_TAGDEFINITION_PRIMARY, de.catma.repository.db.jooq.catmarepository.Keys.KEY_TAGDEFINITION_UK_TDEF_TSDEF_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooq.catmarepository.Keys.FK_TDEF_TAGSETDEFINITIONID, de.catma.repository.db.jooq.catmarepository.Keys.FK_TDEF_PARENTID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition as(java.lang.String alias) {
		return new de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition(alias);
	}
}
