/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taglibrary extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -455956684;

	/**
	 * The singleton instance of <code>CatmaRepository.taglibrary</code>
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Taglibrary TAGLIBRARY = new de.catma.repository.db.jooq.catmarepository.tables.Taglibrary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.taglibrary.tagLibraryID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TAGLIBRARYID = createField("tagLibraryID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.taglibrary.title</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaRepository.taglibrary.publisher</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> PUBLISHER = createField("publisher", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaRepository.taglibrary.author</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaRepository.taglibrary.description</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaRepository.taglibrary.independent</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> INDEPENDENT = createField("independent", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * Create a <code>CatmaRepository.taglibrary</code> table reference
	 */
	public Taglibrary() {
		super("taglibrary", de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.taglibrary</code> table reference
	 */
	public Taglibrary(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooq.catmarepository.tables.Taglibrary.TAGLIBRARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooq.catmarepository.Keys.IDENTITY_TAGLIBRARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooq.catmarepository.Keys.KEY_TAGLIBRARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooq.catmarepository.Keys.KEY_TAGLIBRARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooq.catmarepository.tables.Taglibrary as(java.lang.String alias) {
		return new de.catma.repository.db.jooq.catmarepository.tables.Taglibrary(alias);
	}
}
