/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserdefinedSeparatingcharacter extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 270188873;

	/**
	 * The singleton instance of <code>CatmaRepository.userdefined_separatingcharacter</code>
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter USERDEFINED_SEPARATINGCHARACTER = new de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.userdefined_separatingcharacter.udscID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> UDSCID = createField("udscID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.userdefined_separatingcharacter.chr</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> CHR = createField("chr", org.jooq.impl.SQLDataType.VARCHAR.length(1), this);

	/**
	 * The column <code>CatmaRepository.userdefined_separatingcharacter.sourceDocumentID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> SOURCEDOCUMENTID = createField("sourceDocumentID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>CatmaRepository.userdefined_separatingcharacter</code> table reference
	 */
	public UserdefinedSeparatingcharacter() {
		super("userdefined_separatingcharacter", de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.userdefined_separatingcharacter</code> table reference
	 */
	public UserdefinedSeparatingcharacter(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooq.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter.USERDEFINED_SEPARATINGCHARACTER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooq.catmarepository.Keys.IDENTITY_USERDEFINED_SEPARATINGCHARACTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooq.catmarepository.Keys.KEY_USERDEFINED_SEPARATINGCHARACTER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooq.catmarepository.Keys.KEY_USERDEFINED_SEPARATINGCHARACTER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooq.catmarepository.Keys.FK_UDSC_SOURCEDOCUMENTID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter as(java.lang.String alias) {
		return new de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter(alias);
	}
}
