/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmaindex.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Term extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1308515511;

	/**
	 * The singleton instance of <code>CatmaIndex.term</code>
	 */
	public static final de.catma.repository.db.jooq.catmaindex.tables.Term TERM = new de.catma.repository.db.jooq.catmaindex.tables.Term();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaIndex.term.termID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TERMID = createField("termID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaIndex.term.documentID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DOCUMENTID = createField("documentID", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaIndex.term.frequency</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> FREQUENCY = createField("frequency", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaIndex.term.term</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TERM_ = createField("term", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * Create a <code>CatmaIndex.term</code> table reference
	 */
	public Term() {
		super("term", de.catma.repository.db.jooq.catmaindex.Catmaindex.CATMAINDEX);
	}

	/**
	 * Create an aliased <code>CatmaIndex.term</code> table reference
	 */
	public Term(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooq.catmaindex.Catmaindex.CATMAINDEX, de.catma.repository.db.jooq.catmaindex.tables.Term.TERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooq.catmaindex.Keys.IDENTITY_TERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooq.catmaindex.Keys.KEY_TERM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooq.catmaindex.Keys.KEY_TERM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooq.catmaindex.tables.Term as(java.lang.String alias) {
		return new de.catma.repository.db.jooq.catmaindex.tables.Term(alias);
	}
}
