package de.catma.indexer.db.model;

// Generated 04.05.2012 21:11:20 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Term generated by hbm2java
 */
@Entity
@Table(name = "term", catalog = "CatmaIndex")
public class DBTerm implements java.io.Serializable {

	public static String TABLENAME = "CatmaIndex.term";
	
	private Integer termId;
	private String documentId;
	private int frequency;
	private String term;
	
	public DBTerm() {
	}

	public DBTerm(String documentId, int frequency, String term) {
		this.documentId = documentId;
		this.frequency = frequency;
		this.term = term;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "termID", unique = true, nullable = false)
	public Integer getTermId() {
		return this.termId;
	}

	void setTermId(Integer termId) {
		this.termId = termId;
	}

	@Column(name = "documentID", nullable = false, length = 300)
	public String getDocumentId() {
		return this.documentId;
	}

	void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	@Column(name = "frequency", nullable = false)
	public int getFrequency() {
		return this.frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

	@Column(name = "term", nullable = false, length = 300)
	public String getTerm() {
		return this.term;
	}

	void setTerm(String term) {
		this.term = term;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((documentId == null) ? 0 : documentId.hashCode());
		result = prime * result + frequency;
		result = prime * result + ((term == null) ? 0 : term.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DBTerm other = (DBTerm) obj;
		if (documentId == null) {
			if (other.documentId != null)
				return false;
		} else if (!documentId.equals(other.documentId))
			return false;
		if (frequency != other.frequency)
			return false;
		if (term == null) {
			if (other.term != null)
				return false;
		} else if (!term.equals(other.term))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Term [termId=" + termId + ", documentId=" + documentId
				+ ", frequency=" + frequency + ", term=" + term + "]";
	}
}
