# the public URL of your CATMA instance (currently this must have a trailing slash!)
BASE_URL=https://mydomain.tld/catma/

# temp directory, used when files are uploaded, for example
TEMP_DIR=/pathto/temp

# the public URL of your GitLab instance
GITLAB_SERVER_URL=https://mygitlabinstance.tld
# a valid personal access token with 'api' scope for an admin user on the GitLab instance above
# used to perform certain functions that can't be performed in the context of the regular, logged-in user
# https://docs.gitlab.com/user/profile/personal_access_tokens/
GITLAB_ADMIN_PERSONAL_ACCESS_TOKEN=<your token>

# the directory where user repositories will be cloned on the server to work with them locally
GIT_REPOSITORY_BASE_PATH=/pathto/repo/git

# the directory where the SQLite database used for front page notices is located
SQLITE_DB_BASE_PATH=/pathto/db

# SMTP server details, used to send signup/invitation mails
MAIL_SMTP_HOST=localhost
MAIL_SMTP_PORT=587
MAIL_SMTP_AUTHENTICATION_REQUIRED=false
MAIL_SMTP_USER=XXXXXXXXXXXX
MAIL_SMTP_PASS=XXXXXXXXXXXX
MAIL_FROM=catma-support@mydomain.tld

# Google reCAPTCHA keys, required for the signup form to work
# https://www.google.com/recaptcha/admin
GOOGLE_RECAPTCHA_SITE_KEY=XXXXXXXXXXXX
GOOGLE_RECAPTCHA_SECRET_KEY=XXXXXXXXXXXX

# key used to generate signup tokens, set to a long random value
SIGNUP_TOKEN_KEY=XXXXXXXXXXXX

# optional, but required if you want to allow users to sign in using a Google account
# https://developers.google.com/identity/openid-connect/openid-connect#appsetup
GOOGLE_OAUTH_CLIENT_ID=XXXXXXXXXXXX
GOOGLE_OAUTH_CLIENT_SECRET=XXXXXXXXXXXX

# NB: if you are hosting an instance for public use, you probably want to set the commented URL properties below, in
# addition to RESET_PASSWORD_URL and LOGOUT_URL (which you definitely need to set)
# these all appear on the application landing page, as well as some other places, and default to some location under
# the catma.de domain, so could cause confusion if left unchanged
#ABOUT_URL=
#IMPRINT_URL=
#TERMS_OF_USE_URL=
#PRIVACY_POLICY_URL=
#STATUS_URL=

# the reset password URL of your GitLab instance
RESET_PASSWORD_URL=https://mygitlabinstance.tld/users/password/new
# where users will be directed after logging out
LOGOUT_URL=https://mydomain.tld/catma/

# the directory where the API will clone user repositories on the server to work with them locally; should be a
# different location than GIT_REPOSITORY_BASE_PATH
API_GIT_REPOSITORY_BASE_PATH=/pathto/repo/git_api
# the secret used for the generation of JSON web tokens for the API, set to a long random value
API_HMAC_SECRET=XXXXXXXXXXXX
