/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex;


import de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath;
import de.catma.repository.db.jooqgen.catmaindex.routines.Getterms;
import de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in catmaindex
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>catmaindex.getTagDefinitionPath</code>
	 */
	public static String gettagdefinitionpath(Configuration configuration, Integer curtagdefinitionid) {
		Gettagdefinitionpath f = new Gettagdefinitionpath();
		f.setCurtagdefinitionid(curtagdefinitionid);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>catmaindex.getTagDefinitionPath</code> as a field.
	 */
	public static Field<String> gettagdefinitionpath(Integer curtagdefinitionid) {
		Gettagdefinitionpath f = new Gettagdefinitionpath();
		f.setCurtagdefinitionid(curtagdefinitionid);

		return f.asField();
	}

	/**
	 * Get <code>catmaindex.getTagDefinitionPath</code> as a field.
	 */
	public static Field<String> gettagdefinitionpath(Field<Integer> curtagdefinitionid) {
		Gettagdefinitionpath f = new Gettagdefinitionpath();
		f.setCurtagdefinitionid(curtagdefinitionid);

		return f.asField();
	}

	/**
	 * Call <code>catmaindex.getTerms</code>
	 */
	public static void getterms(Configuration configuration, String docid, Integer basepos, Integer termcount) {
		Getterms p = new Getterms();
		p.setDocid(docid);
		p.setBasepos(basepos);
		p.setTermcount(termcount);

		p.execute(configuration);
	}

	/**
	 * Call <code>catmaindex.searchPhrase</code>
	 */
	public static void searchphrase(Configuration configuration, String term1, String term2, String term3, String term4, String term5, String docid, Byte wild, Integer limitresult) {
		Searchphrase p = new Searchphrase();
		p.setTerm1(term1);
		p.setTerm2(term2);
		p.setTerm3(term3);
		p.setTerm4(term4);
		p.setTerm5(term5);
		p.setDocid(docid);
		p.setWild(wild);
		p.setLimitresult(limitresult);

		p.execute(configuration);
	}
}
