/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all stored procedures and functions in CatmaIndex
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>CatmaIndex.getTagDefinitionPath</code>
	 */
	public static java.lang.String gettagdefinitionpath(org.jooq.Configuration configuration, java.lang.Integer curtagdefinitionid) {
		de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath f = new de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath();
		f.setCurtagdefinitionid(curtagdefinitionid);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>CatmaIndex.getTagDefinitionPath</code> as a field
	 */
	public static org.jooq.Field<java.lang.String> gettagdefinitionpath(java.lang.Integer curtagdefinitionid) {
		de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath f = new de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath();
		f.setCurtagdefinitionid(curtagdefinitionid);

		return f.asField();
	}

	/**
	 * Get <code>CatmaIndex.getTagDefinitionPath</code> as a field
	 */
	public static org.jooq.Field<java.lang.String> gettagdefinitionpath(org.jooq.Field<java.lang.Integer> curtagdefinitionid) {
		de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath f = new de.catma.repository.db.jooqgen.catmaindex.routines.Gettagdefinitionpath();
		f.setCurtagdefinitionid(curtagdefinitionid);

		return f.asField();
	}

	/**
	 * Call <code>CatmaIndex.getTerms</code>
	 */
	public static void getterms(org.jooq.Configuration configuration, java.lang.String docid, java.lang.Integer basepos, java.lang.Integer termcount) {
		de.catma.repository.db.jooqgen.catmaindex.routines.Getterms p = new de.catma.repository.db.jooqgen.catmaindex.routines.Getterms();
		p.setDocid(docid);
		p.setBasepos(basepos);
		p.setTermcount(termcount);

		p.execute(configuration);
	}

	/**
	 * Call <code>CatmaIndex.searchPhrase</code>
	 */
	public static void searchphrase(org.jooq.Configuration configuration, java.lang.String term1, java.lang.String term2, java.lang.String term3, java.lang.String term4, java.lang.String term5, java.lang.String docid, java.lang.Byte wild, java.lang.Integer limitresult) {
		de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase p = new de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase();
		p.setTerm1(term1);
		p.setTerm2(term2);
		p.setTerm3(term3);
		p.setTerm4(term4);
		p.setTerm5(term5);
		p.setDocid(docid);
		p.setWild(wild);
		p.setLimitresult(limitresult);

		p.execute(configuration);
	}
}
