/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex;


import de.catma.repository.db.jooqgen.catmaindex.tables.Position;
import de.catma.repository.db.jooqgen.catmaindex.tables.Property;
import de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference;
import de.catma.repository.db.jooqgen.catmaindex.tables.Term;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in catmaindex
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table catmaindex.position
	 */
	public static final Position POSITION = de.catma.repository.db.jooqgen.catmaindex.tables.Position.POSITION;

	/**
	 * The table catmaindex.property
	 */
	public static final Property PROPERTY = de.catma.repository.db.jooqgen.catmaindex.tables.Property.PROPERTY;

	/**
	 * The table catmaindex.tagreference
	 */
	public static final Tagreference TAGREFERENCE = de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference.TAGREFERENCE;

	/**
	 * The table catmaindex.term
	 */
	public static final Term TERM = de.catma.repository.db.jooqgen.catmaindex.tables.Term.TERM;
}
