/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in CatmaIndex
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table CatmaIndex.position
	 */
	public static final de.catma.repository.db.jooqgen.catmaindex.tables.Position POSITION = de.catma.repository.db.jooqgen.catmaindex.tables.Position.POSITION;

	/**
	 * The table CatmaIndex.property
	 */
	public static final de.catma.repository.db.jooqgen.catmaindex.tables.Property PROPERTY = de.catma.repository.db.jooqgen.catmaindex.tables.Property.PROPERTY;

	/**
	 * The table CatmaIndex.tagreference
	 */
	public static final de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference TAGREFERENCE = de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference.TAGREFERENCE;

	/**
	 * The table CatmaIndex.term
	 */
	public static final de.catma.repository.db.jooqgen.catmaindex.tables.Term TERM = de.catma.repository.db.jooqgen.catmaindex.tables.Term.TERM;
}
