/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.routines;


import de.catma.repository.db.jooqgen.catmaindex.Catmaindex;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gettagdefinitionpath extends AbstractRoutine<String> {

	private static final long serialVersionUID = -1183129037;

	/**
	 * The parameter <code>catmaindex.getTagDefinitionPath.RETURN_VALUE</code>.
	 */
	public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(2048), false);

	/**
	 * The parameter <code>catmaindex.getTagDefinitionPath.curTagDefinitionID</code>.
	 */
	public static final Parameter<Integer> CURTAGDEFINITIONID = createParameter("curTagDefinitionID", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Gettagdefinitionpath() {
		super("getTagDefinitionPath", Catmaindex.CATMAINDEX, org.jooq.impl.SQLDataType.VARCHAR.length(2048));

		setReturnParameter(RETURN_VALUE);
		addInParameter(CURTAGDEFINITIONID);
	}

	/**
	 * Set the <code>curTagDefinitionID</code> parameter IN value to the routine
	 */
	public void setCurtagdefinitionid(Integer value) {
		setValue(CURTAGDEFINITIONID, value);
	}

	/**
	 * Set the <code>curTagDefinitionID</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setCurtagdefinitionid(Field<Integer> field) {
		setField(CURTAGDEFINITIONID, field);
	}
}
