/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.routines;


import de.catma.repository.db.jooqgen.catmaindex.Catmaindex;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Searchphrase extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1940883332;

	/**
	 * The parameter <code>catmaindex.searchPhrase.term1</code>.
	 */
	public static final Parameter<String> TERM1 = createParameter("term1", org.jooq.impl.SQLDataType.VARCHAR.length(300), false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.term2</code>.
	 */
	public static final Parameter<String> TERM2 = createParameter("term2", org.jooq.impl.SQLDataType.VARCHAR.length(300), false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.term3</code>.
	 */
	public static final Parameter<String> TERM3 = createParameter("term3", org.jooq.impl.SQLDataType.VARCHAR.length(300), false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.term4</code>.
	 */
	public static final Parameter<String> TERM4 = createParameter("term4", org.jooq.impl.SQLDataType.VARCHAR.length(300), false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.term5</code>.
	 */
	public static final Parameter<String> TERM5 = createParameter("term5", org.jooq.impl.SQLDataType.VARCHAR.length(300), false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.docID</code>.
	 */
	public static final Parameter<String> DOCID = createParameter("docID", org.jooq.impl.SQLDataType.VARCHAR.length(300), false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.wild</code>.
	 */
	public static final Parameter<Byte> WILD = createParameter("wild", org.jooq.impl.SQLDataType.TINYINT, false);

	/**
	 * The parameter <code>catmaindex.searchPhrase.limitresult</code>.
	 */
	public static final Parameter<Integer> LIMITRESULT = createParameter("limitresult", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Searchphrase() {
		super("searchPhrase", Catmaindex.CATMAINDEX);

		addInParameter(TERM1);
		addInParameter(TERM2);
		addInParameter(TERM3);
		addInParameter(TERM4);
		addInParameter(TERM5);
		addInParameter(DOCID);
		addInParameter(WILD);
		addInParameter(LIMITRESULT);
	}

	/**
	 * Set the <code>term1</code> parameter IN value to the routine
	 */
	public void setTerm1(String value) {
		setValue(TERM1, value);
	}

	/**
	 * Set the <code>term2</code> parameter IN value to the routine
	 */
	public void setTerm2(String value) {
		setValue(TERM2, value);
	}

	/**
	 * Set the <code>term3</code> parameter IN value to the routine
	 */
	public void setTerm3(String value) {
		setValue(TERM3, value);
	}

	/**
	 * Set the <code>term4</code> parameter IN value to the routine
	 */
	public void setTerm4(String value) {
		setValue(TERM4, value);
	}

	/**
	 * Set the <code>term5</code> parameter IN value to the routine
	 */
	public void setTerm5(String value) {
		setValue(TERM5, value);
	}

	/**
	 * Set the <code>docID</code> parameter IN value to the routine
	 */
	public void setDocid(String value) {
		setValue(DOCID, value);
	}

	/**
	 * Set the <code>wild</code> parameter IN value to the routine
	 */
	public void setWild(Byte value) {
		setValue(WILD, value);
	}

	/**
	 * Set the <code>limitresult</code> parameter IN value to the routine
	 */
	public void setLimitresult(Integer value) {
		setValue(LIMITRESULT, value);
	}
}
