/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooq.catmarepository;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in CatmaRepository
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table CatmaRepository.corpus
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Corpus CORPUS = de.catma.repository.db.jooq.catmarepository.tables.Corpus.CORPUS;

	/**
	 * The table CatmaRepository.corpus_sourcedocument
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument CORPUS_SOURCEDOCUMENT = de.catma.repository.db.jooq.catmarepository.tables.CorpusSourcedocument.CORPUS_SOURCEDOCUMENT;

	/**
	 * The table CatmaRepository.corpus_staticmarkupcollection
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.CorpusStaticmarkupcollection CORPUS_STATICMARKUPCOLLECTION = de.catma.repository.db.jooq.catmarepository.tables.CorpusStaticmarkupcollection.CORPUS_STATICMARKUPCOLLECTION;

	/**
	 * The table CatmaRepository.corpus_usermarkupcollection
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.CorpusUsermarkupcollection CORPUS_USERMARKUPCOLLECTION = de.catma.repository.db.jooq.catmarepository.tables.CorpusUsermarkupcollection.CORPUS_USERMARKUPCOLLECTION;

	/**
	 * The table CatmaRepository.property
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Property PROPERTY = de.catma.repository.db.jooq.catmarepository.tables.Property.PROPERTY;

	/**
	 * The table CatmaRepository.propertydefinition
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition PROPERTYDEFINITION = de.catma.repository.db.jooq.catmarepository.tables.Propertydefinition.PROPERTYDEFINITION;

	/**
	 * The table CatmaRepository.propertydef_possiblevalue
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.PropertydefPossiblevalue PROPERTYDEF_POSSIBLEVALUE = de.catma.repository.db.jooq.catmarepository.tables.PropertydefPossiblevalue.PROPERTYDEF_POSSIBLEVALUE;

	/**
	 * The table CatmaRepository.propertyvalue
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Propertyvalue PROPERTYVALUE = de.catma.repository.db.jooq.catmarepository.tables.Propertyvalue.PROPERTYVALUE;

	/**
	 * The table CatmaRepository.sourcedocument
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Sourcedocument SOURCEDOCUMENT = de.catma.repository.db.jooq.catmarepository.tables.Sourcedocument.SOURCEDOCUMENT;

	/**
	 * The table CatmaRepository.staticmarkupattribute
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Staticmarkupattribute STATICMARKUPATTRIBUTE = de.catma.repository.db.jooq.catmarepository.tables.Staticmarkupattribute.STATICMARKUPATTRIBUTE;

	/**
	 * The table CatmaRepository.staticmarkupcollection
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Staticmarkupcollection STATICMARKUPCOLLECTION = de.catma.repository.db.jooq.catmarepository.tables.Staticmarkupcollection.STATICMARKUPCOLLECTION;

	/**
	 * The table CatmaRepository.staticmarkupinstance
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Staticmarkupinstance STATICMARKUPINSTANCE = de.catma.repository.db.jooq.catmarepository.tables.Staticmarkupinstance.STATICMARKUPINSTANCE;

	/**
	 * The table CatmaRepository.tagdefinition
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition TAGDEFINITION = de.catma.repository.db.jooq.catmarepository.tables.Tagdefinition.TAGDEFINITION;

	/**
	 * The table CatmaRepository.taginstance
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Taginstance TAGINSTANCE = de.catma.repository.db.jooq.catmarepository.tables.Taginstance.TAGINSTANCE;

	/**
	 * The table CatmaRepository.taglibrary
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Taglibrary TAGLIBRARY = de.catma.repository.db.jooq.catmarepository.tables.Taglibrary.TAGLIBRARY;

	/**
	 * The table CatmaRepository.tagreference
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Tagreference TAGREFERENCE = de.catma.repository.db.jooq.catmarepository.tables.Tagreference.TAGREFERENCE;

	/**
	 * The table CatmaRepository.tagsetdefinition
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Tagsetdefinition TAGSETDEFINITION = de.catma.repository.db.jooq.catmarepository.tables.Tagsetdefinition.TAGSETDEFINITION;

	/**
	 * The table CatmaRepository.unseparable_charsequence
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UnseparableCharsequence UNSEPARABLE_CHARSEQUENCE = de.catma.repository.db.jooq.catmarepository.tables.UnseparableCharsequence.UNSEPARABLE_CHARSEQUENCE;

	/**
	 * The table CatmaRepository.user
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.User USER = de.catma.repository.db.jooq.catmarepository.tables.User.USER;

	/**
	 * The table CatmaRepository.userdefined_separatingcharacter
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter USERDEFINED_SEPARATINGCHARACTER = de.catma.repository.db.jooq.catmarepository.tables.UserdefinedSeparatingcharacter.USERDEFINED_SEPARATINGCHARACTER;

	/**
	 * The table CatmaRepository.usermarkupcollection
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.Usermarkupcollection USERMARKUPCOLLECTION = de.catma.repository.db.jooq.catmarepository.tables.Usermarkupcollection.USERMARKUPCOLLECTION;

	/**
	 * The table CatmaRepository.user_corpus
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserCorpus USER_CORPUS = de.catma.repository.db.jooq.catmarepository.tables.UserCorpus.USER_CORPUS;

	/**
	 * The table CatmaRepository.user_sourcedocument
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserSourcedocument USER_SOURCEDOCUMENT = de.catma.repository.db.jooq.catmarepository.tables.UserSourcedocument.USER_SOURCEDOCUMENT;

	/**
	 * The table CatmaRepository.user_staticmarkupcollection
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserStaticmarkupcollection USER_STATICMARKUPCOLLECTION = de.catma.repository.db.jooq.catmarepository.tables.UserStaticmarkupcollection.USER_STATICMARKUPCOLLECTION;

	/**
	 * The table CatmaRepository.user_taglibrary
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserTaglibrary USER_TAGLIBRARY = de.catma.repository.db.jooq.catmarepository.tables.UserTaglibrary.USER_TAGLIBRARY;

	/**
	 * The table CatmaRepository.user_usermarkupcollection
	 */
	public static final de.catma.repository.db.jooq.catmarepository.tables.UserUsermarkupcollection USER_USERMARKUPCOLLECTION = de.catma.repository.db.jooq.catmarepository.tables.UserUsermarkupcollection.USER_USERMARKUPCOLLECTION;
}
