/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex;


import de.catma.repository.db.jooqgen.catmaindex.tables.Position;
import de.catma.repository.db.jooqgen.catmaindex.tables.Property;
import de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference;
import de.catma.repository.db.jooqgen.catmaindex.tables.Term;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Catmaindex extends SchemaImpl {

	private static final long serialVersionUID = -1136861552;

	/**
	 * The reference instance of <code>catmaindex</code>
	 */
	public static final Catmaindex CATMAINDEX = new Catmaindex();

	/**
	 * No further instances allowed
	 */
	private Catmaindex() {
		super("catmaindex");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Position.POSITION,
			Property.PROPERTY,
			Tagreference.TAGREFERENCE,
			Term.TERM);
	}
}
