/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gettagdefinitionchildren extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -307341387;

	/**
	 * The parameter <code>CatmaRepository.getTagDefinitionChildren.startTagDefinitionID</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Integer> STARTTAGDEFINITIONID = createParameter("startTagDefinitionID", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * Create a new routine call instance
	 */
	public Gettagdefinitionchildren() {
		super("getTagDefinitionChildren", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);

		addInParameter(STARTTAGDEFINITIONID);
	}

	/**
	 * Set the <code>startTagDefinitionID</code> parameter IN value to the routine
	 */
	public void setStarttagdefinitionid(java.lang.Integer value) {
		setValue(de.catma.repository.db.jooqgen.catmarepository.routines.Gettagdefinitionchildren.STARTTAGDEFINITIONID, value);
	}
}
