/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.tables;


import de.catma.repository.db.jooqgen.catmaindex.Catmaindex;
import de.catma.repository.db.jooqgen.catmaindex.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Property extends TableImpl<Record> {

	private static final long serialVersionUID = -71053528;

	/**
	 * The reference instance of <code>catmaindex.property</code>
	 */
	public static final Property PROPERTY = new Property();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmaindex.property.propertyID</code>.
	 */
	public final TableField<Record, Integer> PROPERTYID = createField("propertyID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmaindex.property.tagInstanceID</code>.
	 */
	public final TableField<Record, byte[]> TAGINSTANCEID = createField("tagInstanceID", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>catmaindex.property.propertyDefinitionID</code>.
	 */
	public final TableField<Record, byte[]> PROPERTYDEFINITIONID = createField("propertyDefinitionID", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>catmaindex.property.name</code>.
	 */
	public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>catmaindex.property.value</code>.
	 */
	public final TableField<Record, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>catmaindex.property</code> table reference
	 */
	public Property() {
		this("property", null);
	}

	/**
	 * Create an aliased <code>catmaindex.property</code> table reference
	 */
	public Property(String alias) {
		this(alias, PROPERTY);
	}

	private Property(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Property(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmaindex.CATMAINDEX, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_PROPERTY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_PROPERTY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PROPERTY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Property as(String alias) {
		return new Property(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Property rename(String name) {
		return new Property(name, null);
	}
}
