/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagreference extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1332970545;

	/**
	 * The singleton instance of <code>CatmaIndex.tagreference</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference TAGREFERENCE = new de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaIndex.tagreference.tagReferenceID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TAGREFERENCEID = createField("tagReferenceID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaIndex.tagreference.documentID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> DOCUMENTID = createField("documentID", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaIndex.tagreference.userMarkupCollectionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> USERMARKUPCOLLECTIONID = createField("userMarkupCollectionID", org.jooq.impl.SQLDataType.VARCHAR.length(300), this);

	/**
	 * The column <code>CatmaIndex.tagreference.tagDefinitionPath</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TAGDEFINITIONPATH = createField("tagDefinitionPath", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this);

	/**
	 * The column <code>CatmaIndex.tagreference.tagDefinitionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, byte[]> TAGDEFINITIONID = createField("tagDefinitionID", org.jooq.impl.SQLDataType.BINARY.length(16), this);

	/**
	 * The column <code>CatmaIndex.tagreference.tagInstanceID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, byte[]> TAGINSTANCEID = createField("tagInstanceID", org.jooq.impl.SQLDataType.BINARY.length(16), this);

	/**
	 * The column <code>CatmaIndex.tagreference.tagDefinitionVersion</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TAGDEFINITIONVERSION = createField("tagDefinitionVersion", org.jooq.impl.SQLDataType.VARCHAR.length(28), this);

	/**
	 * The column <code>CatmaIndex.tagreference.characterStart</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CHARACTERSTART = createField("characterStart", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaIndex.tagreference.characterEnd</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> CHARACTEREND = createField("characterEnd", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>CatmaIndex.tagreference</code> table reference
	 */
	public Tagreference() {
		super("tagreference", de.catma.repository.db.jooqgen.catmaindex.Catmaindex.CATMAINDEX);
	}

	/**
	 * Create an aliased <code>CatmaIndex.tagreference</code> table reference
	 */
	public Tagreference(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmaindex.Catmaindex.CATMAINDEX, de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference.TAGREFERENCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmaindex.Keys.IDENTITY_TAGREFERENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmaindex.Keys.KEY_TAGREFERENCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmaindex.Keys.KEY_TAGREFERENCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmaindex.tables.Tagreference(alias);
	}
}
