/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.tables;


import de.catma.repository.db.jooqgen.catmaindex.Catmaindex;
import de.catma.repository.db.jooqgen.catmaindex.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Term extends TableImpl<Record> {

	private static final long serialVersionUID = 1378232418;

	/**
	 * The reference instance of <code>catmaindex.term</code>
	 */
	public static final Term TERM = new Term();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmaindex.term.termID</code>.
	 */
	public final TableField<Record, Integer> TERMID = createField("termID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmaindex.term.documentID</code>.
	 */
	public final TableField<Record, String> DOCUMENTID = createField("documentID", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false), this, "");

	/**
	 * The column <code>catmaindex.term.frequency</code>.
	 */
	public final TableField<Record, Integer> FREQUENCY = createField("frequency", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmaindex.term.term</code>.
	 */
	public final TableField<Record, String> TERM_ = createField("term", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false), this, "");

	/**
	 * Create a <code>catmaindex.term</code> table reference
	 */
	public Term() {
		this("term", null);
	}

	/**
	 * Create an aliased <code>catmaindex.term</code> table reference
	 */
	public Term(String alias) {
		this(alias, TERM);
	}

	private Term(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Term(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmaindex.CATMAINDEX, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_TERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_TERM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_TERM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Term as(String alias) {
		return new Term(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Term rename(String name) {
		return new Term(name, null);
	}
}
