/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reindex extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1587113842;

	/**
	 * Create a new routine call instance
	 */
	public Reindex() {
		super("reindex", de.catma.repository.db.jooqgen.catmaindex.Catmaindex.CATMAINDEX);
	}
}
