/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmaindex.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Searchphrase extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1234744519;

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.term1</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> TERM1 = createParameter("term1", org.jooq.impl.SQLDataType.VARCHAR.length(300));

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.term2</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> TERM2 = createParameter("term2", org.jooq.impl.SQLDataType.VARCHAR.length(300));

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.term3</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> TERM3 = createParameter("term3", org.jooq.impl.SQLDataType.VARCHAR.length(300));

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.term4</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> TERM4 = createParameter("term4", org.jooq.impl.SQLDataType.VARCHAR.length(300));

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.term5</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> TERM5 = createParameter("term5", org.jooq.impl.SQLDataType.VARCHAR.length(300));

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.docID</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> DOCID = createParameter("docID", org.jooq.impl.SQLDataType.VARCHAR.length(300));

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.wild</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Byte> WILD = createParameter("wild", org.jooq.impl.SQLDataType.TINYINT);

	/**
	 * The parameter <code>CatmaIndex.searchPhrase.limitresult</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Integer> LIMITRESULT = createParameter("limitresult", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * Create a new routine call instance
	 */
	public Searchphrase() {
		super("searchPhrase", de.catma.repository.db.jooqgen.catmaindex.Catmaindex.CATMAINDEX);

		addInParameter(TERM1);
		addInParameter(TERM2);
		addInParameter(TERM3);
		addInParameter(TERM4);
		addInParameter(TERM5);
		addInParameter(DOCID);
		addInParameter(WILD);
		addInParameter(LIMITRESULT);
	}

	/**
	 * Set the <code>term1</code> parameter IN value to the routine
	 */
	public void setTerm1(java.lang.String value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.TERM1, value);
	}

	/**
	 * Set the <code>term2</code> parameter IN value to the routine
	 */
	public void setTerm2(java.lang.String value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.TERM2, value);
	}

	/**
	 * Set the <code>term3</code> parameter IN value to the routine
	 */
	public void setTerm3(java.lang.String value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.TERM3, value);
	}

	/**
	 * Set the <code>term4</code> parameter IN value to the routine
	 */
	public void setTerm4(java.lang.String value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.TERM4, value);
	}

	/**
	 * Set the <code>term5</code> parameter IN value to the routine
	 */
	public void setTerm5(java.lang.String value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.TERM5, value);
	}

	/**
	 * Set the <code>docID</code> parameter IN value to the routine
	 */
	public void setDocid(java.lang.String value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.DOCID, value);
	}

	/**
	 * Set the <code>wild</code> parameter IN value to the routine
	 */
	public void setWild(java.lang.Byte value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.WILD, value);
	}

	/**
	 * Set the <code>limitresult</code> parameter IN value to the routine
	 */
	public void setLimitresult(java.lang.Integer value) {
		setValue(de.catma.repository.db.jooqgen.catmaindex.routines.Searchphrase.LIMITRESULT, value);
	}
}
