/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpusUsermarkupcollection extends TableImpl<Record> {

	private static final long serialVersionUID = -2068538712;

	/**
	 * The reference instance of <code>catmarepository.corpus_usermarkupcollection</code>
	 */
	public static final CorpusUsermarkupcollection CORPUS_USERMARKUPCOLLECTION = new CorpusUsermarkupcollection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.corpus_usermarkupcollection.corpus_usermarkupcollectionID</code>.
	 */
	public final TableField<Record, Integer> CORPUS_USERMARKUPCOLLECTIONID = createField("corpus_usermarkupcollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.corpus_usermarkupcollection.corpusID</code>.
	 */
	public final TableField<Record, Integer> CORPUSID = createField("corpusID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.corpus_usermarkupcollection.userMarkupCollectionID</code>.
	 */
	public final TableField<Record, Integer> USERMARKUPCOLLECTIONID = createField("userMarkupCollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.corpus_usermarkupcollection</code> table reference
	 */
	public CorpusUsermarkupcollection() {
		this("corpus_usermarkupcollection", null);
	}

	/**
	 * Create an aliased <code>catmarepository.corpus_usermarkupcollection</code> table reference
	 */
	public CorpusUsermarkupcollection(String alias) {
		this(alias, CORPUS_USERMARKUPCOLLECTION);
	}

	private CorpusUsermarkupcollection(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private CorpusUsermarkupcollection(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_CORPUS_USERMARKUPCOLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_CORPUS_USERMARKUPCOLLECTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_CORPUS_USERMARKUPCOLLECTION_PRIMARY, Keys.KEY_CORPUS_USERMARKUPCOLLECTION_UK_CORPUSUMC_CORPUSID_UMCID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_CORPUSUMC_CORPUSID, Keys.FK_CORPUSUMC_USERMARKUPCOLLECTIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CorpusUsermarkupcollection as(String alias) {
		return new CorpusUsermarkupcollection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CorpusUsermarkupcollection rename(String name) {
		return new CorpusUsermarkupcollection(name, null);
	}
}
