/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaintenanceSem extends TableImpl<Record> {

	private static final long serialVersionUID = -457108915;

	/**
	 * The reference instance of <code>catmarepository.maintenance_sem</code>
	 */
	public static final MaintenanceSem MAINTENANCE_SEM = new MaintenanceSem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.maintenance_sem.maintenance_semID</code>.
	 */
	public final TableField<Record, Integer> MAINTENANCE_SEMID = createField("maintenance_semID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.maintenance_sem.type</code>. CLEANING
IMPORT
SYNCH
	 */
	public final TableField<Record, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "CLEANING\nIMPORT\nSYNCH");

	/**
	 * The column <code>catmarepository.maintenance_sem.starttime</code>.
	 */
	public final TableField<Record, Timestamp> STARTTIME = createField("starttime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>catmarepository.maintenance_sem</code> table reference
	 */
	public MaintenanceSem() {
		this("maintenance_sem", null);
	}

	/**
	 * Create an aliased <code>catmarepository.maintenance_sem</code> table reference
	 */
	public MaintenanceSem(String alias) {
		this(alias, MAINTENANCE_SEM);
	}

	private MaintenanceSem(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private MaintenanceSem(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_MAINTENANCE_SEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_MAINTENANCE_SEM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_MAINTENANCE_SEM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MaintenanceSem as(String alias) {
		return new MaintenanceSem(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MaintenanceSem rename(String name) {
		return new MaintenanceSem(name, null);
	}
}
