/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaintenanceSem extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = -220613133;

	/**
	 * The singleton instance of <code>CatmaRepository.maintenance_sem</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem MAINTENANCE_SEM = new de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.maintenance_sem.maintenance_semID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> MAINTENANCE_SEMID = createField("maintenance_semID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.maintenance_sem.type</code>. CLEANING
IMPORT
SYNCH
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>CatmaRepository.maintenance_sem.starttime</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.sql.Timestamp> STARTTIME = createField("starttime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>CatmaRepository.maintenance_sem</code> table reference
	 */
	public MaintenanceSem() {
		super("maintenance_sem", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.maintenance_sem</code> table reference
	 */
	public MaintenanceSem(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem.MAINTENANCE_SEM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_MAINTENANCE_SEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_MAINTENANCE_SEM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_MAINTENANCE_SEM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem(alias);
	}
}
