/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mlog extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1628871478;

	/**
	 * The singleton instance of <code>CatmaRepository.mlog</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.Mlog MLOG = new de.catma.repository.db.jooqgen.catmarepository.tables.Mlog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.mlog.id</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.mlog.log</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> LOG = createField("log", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>CatmaRepository.mlog</code> table reference
	 */
	public Mlog() {
		super("mlog", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.mlog</code> table reference
	 */
	public Mlog(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.Mlog.MLOG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_MLOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_MLOG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_MLOG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.Mlog as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.Mlog(alias);
	}
}
