/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permission extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1524075615;

	/**
	 * The singleton instance of <code>CatmaRepository.permission</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.Permission PERMISSION = new de.catma.repository.db.jooqgen.catmarepository.tables.Permission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.permission.permissionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> PERMISSIONID = createField("permissionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.permission.identifier</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>CatmaRepository.permission</code> table reference
	 */
	public Permission() {
		super("permission", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.permission</code> table reference
	 */
	public Permission(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.Permission.PERMISSION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_PERMISSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_PERMISSION_PRIMARY, de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_PERMISSION_UK_PERM_IDENTIFIER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.Permission as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.Permission(alias);
	}
}
