/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permission extends TableImpl<Record> {

	private static final long serialVersionUID = 1630766245;

	/**
	 * The reference instance of <code>catmarepository.permission</code>
	 */
	public static final Permission PERMISSION = new Permission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.permission.permissionID</code>.
	 */
	public final TableField<Record, Integer> PERMISSIONID = createField("permissionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.permission.identifier</code>.
	 */
	public final TableField<Record, String> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.permission</code> table reference
	 */
	public Permission() {
		this("permission", null);
	}

	/**
	 * Create an aliased <code>catmarepository.permission</code> table reference
	 */
	public Permission(String alias) {
		this(alias, PERMISSION);
	}

	private Permission(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Permission(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_PERMISSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERMISSION_PRIMARY, Keys.KEY_PERMISSION_UK_PERM_IDENTIFIER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Permission as(String alias) {
		return new Permission(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Permission rename(String name) {
		return new Permission(name, null);
	}
}
