/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertydefPossiblevalue extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1674843738;

	/**
	 * The singleton instance of <code>CatmaRepository.propertydef_possiblevalue</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue PROPERTYDEF_POSSIBLEVALUE = new de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.propertydef_possiblevalue.propertydefPossibleValueID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> PROPERTYDEFPOSSIBLEVALUEID = createField("propertydefPossibleValueID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.propertydef_possiblevalue.value</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>CatmaRepository.propertydef_possiblevalue.propertyDefinitionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> PROPERTYDEFINITIONID = createField("propertyDefinitionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>CatmaRepository.propertydef_possiblevalue</code> table reference
	 */
	public PropertydefPossiblevalue() {
		super("propertydef_possiblevalue", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.propertydef_possiblevalue</code> table reference
	 */
	public PropertydefPossiblevalue(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue.PROPERTYDEF_POSSIBLEVALUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_PROPERTYDEF_POSSIBLEVALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_PROPERTYDEF_POSSIBLEVALUE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_PROPERTYDEF_POSSIBLEVALUE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.FK_PPV_PROPERTYDEFINITIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue(alias);
	}
}
