/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Propertyvalue extends TableImpl<Record> {

	private static final long serialVersionUID = 946430079;

	/**
	 * The reference instance of <code>catmarepository.propertyvalue</code>
	 */
	public static final Propertyvalue PROPERTYVALUE = new Propertyvalue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.propertyvalue.propertyValueID</code>.
	 */
	public final TableField<Record, Integer> PROPERTYVALUEID = createField("propertyValueID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.propertyvalue.propertyID</code>.
	 */
	public final TableField<Record, Integer> PROPERTYID = createField("propertyID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.propertyvalue.value</code>.
	 */
	public final TableField<Record, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>catmarepository.propertyvalue</code> table reference
	 */
	public Propertyvalue() {
		this("propertyvalue", null);
	}

	/**
	 * Create an aliased <code>catmarepository.propertyvalue</code> table reference
	 */
	public Propertyvalue(String alias) {
		this(alias, PROPERTYVALUE);
	}

	private Propertyvalue(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Propertyvalue(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_PROPERTYVALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_PROPERTYVALUE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PROPERTYVALUE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_PROPV_PROPERTYID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Propertyvalue as(String alias) {
		return new Propertyvalue(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Propertyvalue rename(String name) {
		return new Propertyvalue(name, null);
	}
}
