/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermission extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 35066587;

	/**
	 * The singleton instance of <code>CatmaRepository.role_permission</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission ROLE_PERMISSION = new de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.role_permission.role_permissionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> ROLE_PERMISSIONID = createField("role_permissionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.role_permission.roleID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> ROLEID = createField("roleID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.role_permission.permissionID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> PERMISSIONID = createField("permissionID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>CatmaRepository.role_permission</code> table reference
	 */
	public RolePermission() {
		super("role_permission", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.role_permission</code> table reference
	 */
	public RolePermission(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission.ROLE_PERMISSION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_ROLE_PERMISSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_ROLE_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_ROLE_PERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.FK_ROLE_PERM_ROLEID, de.catma.repository.db.jooqgen.catmarepository.Keys.FK_ROLE_PERM_PERMISSIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission(alias);
	}
}
