/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1222866433;

	/**
	 * The singleton instance of <code>CatmaRepository.role</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.Role ROLE = new de.catma.repository.db.jooqgen.catmarepository.tables.Role();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.role.roleID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> ROLEID = createField("roleID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.role.identifier</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.String> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * Create a <code>CatmaRepository.role</code> table reference
	 */
	public Role() {
		super("role", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.role</code> table reference
	 */
	public Role(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.Role.ROLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_ROLE_PRIMARY, de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_ROLE_UK_ROLE_IDENTIFIER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.Role as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.Role(alias);
	}
}
