/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sourcedocument extends TableImpl<Record> {

	private static final long serialVersionUID = 906329342;

	/**
	 * The reference instance of <code>catmarepository.sourcedocument</code>
	 */
	public static final Sourcedocument SOURCEDOCUMENT = new Sourcedocument();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.sourcedocument.sourceDocumentID</code>.
	 */
	public final TableField<Record, Integer> SOURCEDOCUMENTID = createField("sourceDocumentID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.title</code>.
	 */
	public final TableField<Record, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.publisher</code>.
	 */
	public final TableField<Record, String> PUBLISHER = createField("publisher", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.author</code>.
	 */
	public final TableField<Record, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.description</code>.
	 */
	public final TableField<Record, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.sourceUri</code>.
	 */
	public final TableField<Record, String> SOURCEURI = createField("sourceUri", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.fileType</code>.
	 */
	public final TableField<Record, String> FILETYPE = createField("fileType", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.charset</code>.
	 */
	public final TableField<Record, String> CHARSET = createField("charset", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.fileOSType</code>.
	 */
	public final TableField<Record, String> FILEOSTYPE = createField("fileOSType", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.checksum</code>.
	 */
	public final TableField<Record, Long> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.mimeType</code>.
	 */
	public final TableField<Record, String> MIMETYPE = createField("mimeType", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.xsltDocumentLocalUri</code>.
	 */
	public final TableField<Record, String> XSLTDOCUMENTLOCALURI = createField("xsltDocumentLocalUri", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.locale</code>.
	 */
	public final TableField<Record, String> LOCALE = createField("locale", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.sourcedocument.localUri</code>.
	 */
	public final TableField<Record, String> LOCALURI = createField("localUri", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * Create a <code>catmarepository.sourcedocument</code> table reference
	 */
	public Sourcedocument() {
		this("sourcedocument", null);
	}

	/**
	 * Create an aliased <code>catmarepository.sourcedocument</code> table reference
	 */
	public Sourcedocument(String alias) {
		this(alias, SOURCEDOCUMENT);
	}

	private Sourcedocument(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Sourcedocument(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_SOURCEDOCUMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_SOURCEDOCUMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_SOURCEDOCUMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Sourcedocument as(String alias) {
		return new Sourcedocument(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Sourcedocument rename(String name) {
		return new Sourcedocument(name, null);
	}
}
