/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staticmarkupcollection extends TableImpl<Record> {

	private static final long serialVersionUID = 10341245;

	/**
	 * The reference instance of <code>catmarepository.staticmarkupcollection</code>
	 */
	public static final Staticmarkupcollection STATICMARKUPCOLLECTION = new Staticmarkupcollection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.staticmarkupcollection.staticMarkupCollectionID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPCOLLECTIONID = createField("staticMarkupCollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupcollection.name</code>.
	 */
	public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupcollection.sourceDocumentID</code>.
	 */
	public final TableField<Record, Integer> SOURCEDOCUMENTID = createField("sourceDocumentID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.staticmarkupcollection</code> table reference
	 */
	public Staticmarkupcollection() {
		this("staticmarkupcollection", null);
	}

	/**
	 * Create an aliased <code>catmarepository.staticmarkupcollection</code> table reference
	 */
	public Staticmarkupcollection(String alias) {
		this(alias, STATICMARKUPCOLLECTION);
	}

	private Staticmarkupcollection(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Staticmarkupcollection(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_STATICMARKUPCOLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_STATICMARKUPCOLLECTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_STATICMARKUPCOLLECTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_STATICMC_SOURCEDOCUMENTID00);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Staticmarkupcollection as(String alias) {
		return new Staticmarkupcollection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Staticmarkupcollection rename(String name) {
		return new Staticmarkupcollection(name, null);
	}
}
