/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taginstance extends TableImpl<Record> {

	private static final long serialVersionUID = 1551740921;

	/**
	 * The reference instance of <code>catmarepository.taginstance</code>
	 */
	public static final Taginstance TAGINSTANCE = new Taginstance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.taginstance.tagInstanceID</code>.
	 */
	public final TableField<Record, Integer> TAGINSTANCEID = createField("tagInstanceID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.taginstance.uuid</code>.
	 */
	public final TableField<Record, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.taginstance.tagDefinitionID</code>.
	 */
	public final TableField<Record, Integer> TAGDEFINITIONID = createField("tagDefinitionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.taginstance</code> table reference
	 */
	public Taginstance() {
		this("taginstance", null);
	}

	/**
	 * Create an aliased <code>catmarepository.taginstance</code> table reference
	 */
	public Taginstance(String alias) {
		this(alias, TAGINSTANCE);
	}

	private Taginstance(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Taginstance(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_TAGINSTANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_TAGINSTANCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_TAGINSTANCE_PRIMARY, Keys.KEY_TAGINSTANCE_UK_TI_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_TI_TAGDEFINITIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Taginstance as(String alias) {
		return new Taginstance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Taginstance rename(String name) {
		return new Taginstance(name, null);
	}
}
