/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taglibrary extends TableImpl<Record> {

	private static final long serialVersionUID = 1934436632;

	/**
	 * The reference instance of <code>catmarepository.taglibrary</code>
	 */
	public static final Taglibrary TAGLIBRARY = new Taglibrary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.taglibrary.tagLibraryID</code>.
	 */
	public final TableField<Record, Integer> TAGLIBRARYID = createField("tagLibraryID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.taglibrary.title</code>.
	 */
	public final TableField<Record, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.taglibrary.publisher</code>.
	 */
	public final TableField<Record, String> PUBLISHER = createField("publisher", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.taglibrary.author</code>.
	 */
	public final TableField<Record, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.taglibrary.description</code>.
	 */
	public final TableField<Record, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(300).defaulted(true), this, "");

	/**
	 * The column <code>catmarepository.taglibrary.independent</code>.
	 */
	public final TableField<Record, Byte> INDEPENDENT = createField("independent", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.taglibrary</code> table reference
	 */
	public Taglibrary() {
		this("taglibrary", null);
	}

	/**
	 * Create an aliased <code>catmarepository.taglibrary</code> table reference
	 */
	public Taglibrary(String alias) {
		this(alias, TAGLIBRARY);
	}

	private Taglibrary(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Taglibrary(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_TAGLIBRARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_TAGLIBRARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_TAGLIBRARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Taglibrary as(String alias) {
		return new Taglibrary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Taglibrary rename(String name) {
		return new Taglibrary(name, null);
	}
}
