/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCorpus extends TableImpl<Record> {

	private static final long serialVersionUID = 2077638787;

	/**
	 * The reference instance of <code>catmarepository.user_corpus</code>
	 */
	public static final UserCorpus USER_CORPUS = new UserCorpus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.user_corpus.user_corpusID</code>.
	 */
	public final TableField<Record, Integer> USER_CORPUSID = createField("user_corpusID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_corpus.userID</code>.
	 */
	public final TableField<Record, Integer> USERID = createField("userID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_corpus.corpusID</code>.
	 */
	public final TableField<Record, Integer> CORPUSID = createField("corpusID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_corpus.accessMode</code>.
	 */
	public final TableField<Record, Integer> ACCESSMODE = createField("accessMode", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_corpus.owner</code>.
	 */
	public final TableField<Record, Byte> OWNER = createField("owner", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.user_corpus</code> table reference
	 */
	public UserCorpus() {
		this("user_corpus", null);
	}

	/**
	 * Create an aliased <code>catmarepository.user_corpus</code> table reference
	 */
	public UserCorpus(String alias) {
		this(alias, USER_CORPUS);
	}

	private UserCorpus(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserCorpus(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_USER_CORPUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_USER_CORPUS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_USER_CORPUS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_USERCORPUS_USERID, Keys.FK_USERCORPUS_CORPUSID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCorpus as(String alias) {
		return new UserCorpus(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserCorpus rename(String name) {
		return new UserCorpus(name, null);
	}
}
