/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStaticmarkupcollection extends TableImpl<Record> {

	private static final long serialVersionUID = 1484936565;

	/**
	 * The reference instance of <code>catmarepository.user_staticmarkupcollection</code>
	 */
	public static final UserStaticmarkupcollection USER_STATICMARKUPCOLLECTION = new UserStaticmarkupcollection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.user_staticmarkupcollection.user_staticmarkupcollectionID</code>.
	 */
	public final TableField<Record, Integer> USER_STATICMARKUPCOLLECTIONID = createField("user_staticmarkupcollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_staticmarkupcollection.userID</code>.
	 */
	public final TableField<Record, Integer> USERID = createField("userID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_staticmarkupcollection.staticMarkupCollectionID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPCOLLECTIONID = createField("staticMarkupCollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_staticmarkupcollection.accessMode</code>.
	 */
	public final TableField<Record, Integer> ACCESSMODE = createField("accessMode", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_staticmarkupcollection.owner</code>.
	 */
	public final TableField<Record, Byte> OWNER = createField("owner", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.user_staticmarkupcollection</code> table reference
	 */
	public UserStaticmarkupcollection() {
		this("user_staticmarkupcollection", null);
	}

	/**
	 * Create an aliased <code>catmarepository.user_staticmarkupcollection</code> table reference
	 */
	public UserStaticmarkupcollection(String alias) {
		this(alias, USER_STATICMARKUPCOLLECTION);
	}

	private UserStaticmarkupcollection(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserStaticmarkupcollection(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_USER_STATICMARKUPCOLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_USER_STATICMARKUPCOLLECTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_USER_STATICMARKUPCOLLECTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_USERSMC_USERID, Keys.FK_USERSMC_STATICMARKUPCOLLECTIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserStaticmarkupcollection as(String alias) {
		return new UserStaticmarkupcollection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserStaticmarkupcollection rename(String name) {
		return new UserStaticmarkupcollection(name, null);
	}
}
