/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserUsermarkupcollection extends TableImpl<Record> {

	private static final long serialVersionUID = 980329335;

	/**
	 * The reference instance of <code>catmarepository.user_usermarkupcollection</code>
	 */
	public static final UserUsermarkupcollection USER_USERMARKUPCOLLECTION = new UserUsermarkupcollection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.user_usermarkupcollection.user_usermarkupcollectioID</code>.
	 */
	public final TableField<Record, Integer> USER_USERMARKUPCOLLECTIOID = createField("user_usermarkupcollectioID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_usermarkupcollection.userID</code>.
	 */
	public final TableField<Record, Integer> USERID = createField("userID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_usermarkupcollection.userMarkupCollectionID</code>.
	 */
	public final TableField<Record, Integer> USERMARKUPCOLLECTIONID = createField("userMarkupCollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_usermarkupcollection.accessMode</code>.
	 */
	public final TableField<Record, Integer> ACCESSMODE = createField("accessMode", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_usermarkupcollection.owner</code>.
	 */
	public final TableField<Record, Byte> OWNER = createField("owner", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.user_usermarkupcollection</code> table reference
	 */
	public UserUsermarkupcollection() {
		this("user_usermarkupcollection", null);
	}

	/**
	 * Create an aliased <code>catmarepository.user_usermarkupcollection</code> table reference
	 */
	public UserUsermarkupcollection(String alias) {
		this(alias, USER_USERMARKUPCOLLECTION);
	}

	private UserUsermarkupcollection(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserUsermarkupcollection(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_USER_USERMARKUPCOLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_USER_USERMARKUPCOLLECTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_USER_USERMARKUPCOLLECTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_USERUMC_USERID, Keys.FK_USERUMC_USERMARKUPCOLLECTIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserUsermarkupcollection as(String alias) {
		return new UserUsermarkupcollection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserUsermarkupcollection rename(String name) {
		return new UserUsermarkupcollection(name, null);
	}
}
