/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRole extends TableImpl<Record> {

	private static final long serialVersionUID = -1616589586;

	/**
	 * The reference instance of <code>catmarepository.user_role</code>
	 */
	public static final UserRole USER_ROLE = new UserRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.user_role.user_roleID</code>.
	 */
	public final TableField<Record, Integer> USER_ROLEID = createField("user_roleID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_role.userID</code>.
	 */
	public final TableField<Record, Integer> USERID = createField("userID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.user_role.roleID</code>.
	 */
	public final TableField<Record, Integer> ROLEID = createField("roleID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.user_role</code> table reference
	 */
	public UserRole() {
		this("user_role", null);
	}

	/**
	 * Create an aliased <code>catmarepository.user_role</code> table reference
	 */
	public UserRole(String alias) {
		this(alias, USER_ROLE);
	}

	private UserRole(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserRole(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_USER_ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_USER_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_USER_ROLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_USER_ROLE_USERID, Keys.FK_USER_ROLE_ROLEID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRole as(String alias) {
		return new UserRole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserRole rename(String name) {
		return new UserRole(name, null);
	}
}
