/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTaglibrary extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 272383683;

	/**
	 * The singleton instance of <code>CatmaRepository.user_taglibrary</code>
	 */
	public static final de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary USER_TAGLIBRARY = new de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>CatmaRepository.user_taglibrary.user_tagLibraryID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> USER_TAGLIBRARYID = createField("user_tagLibraryID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.user_taglibrary.userID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> USERID = createField("userID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.user_taglibrary.tagLibraryID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> TAGLIBRARYID = createField("tagLibraryID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.user_taglibrary.accessMode</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Integer> ACCESSMODE = createField("accessMode", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>CatmaRepository.user_taglibrary.owner</code>. 
	 */
	public final org.jooq.TableField<org.jooq.Record, java.lang.Byte> OWNER = createField("owner", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * Create a <code>CatmaRepository.user_taglibrary</code> table reference
	 */
	public UserTaglibrary() {
		super("user_taglibrary", de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY);
	}

	/**
	 * Create an aliased <code>CatmaRepository.user_taglibrary</code> table reference
	 */
	public UserTaglibrary(java.lang.String alias) {
		super(alias, de.catma.repository.db.jooqgen.catmarepository.Catmarepository.CATMAREPOSITORY, de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary.USER_TAGLIBRARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.Record, java.lang.Integer> getIdentity() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.IDENTITY_USER_TAGLIBRARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.Record> getPrimaryKey() {
		return de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_USER_TAGLIBRARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.Record>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.KEY_USER_TAGLIBRARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.Record, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.Record, ?>>asList(de.catma.repository.db.jooqgen.catmarepository.Keys.FK_USERTL_USERID, de.catma.repository.db.jooqgen.catmarepository.Keys.FK_USERTL_TAGLIBRARYID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary as(java.lang.String alias) {
		return new de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary(alias);
	}
}
