/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserdefinedSeparatingcharacter extends TableImpl<Record> {

	private static final long serialVersionUID = 326060398;

	/**
	 * The reference instance of <code>catmarepository.userdefined_separatingcharacter</code>
	 */
	public static final UserdefinedSeparatingcharacter USERDEFINED_SEPARATINGCHARACTER = new UserdefinedSeparatingcharacter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.userdefined_separatingcharacter.udscID</code>.
	 */
	public final TableField<Record, Integer> UDSCID = createField("udscID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.userdefined_separatingcharacter.chr</code>.
	 */
	public final TableField<Record, String> CHR = createField("chr", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.userdefined_separatingcharacter.sourceDocumentID</code>.
	 */
	public final TableField<Record, Integer> SOURCEDOCUMENTID = createField("sourceDocumentID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.userdefined_separatingcharacter</code> table reference
	 */
	public UserdefinedSeparatingcharacter() {
		this("userdefined_separatingcharacter", null);
	}

	/**
	 * Create an aliased <code>catmarepository.userdefined_separatingcharacter</code> table reference
	 */
	public UserdefinedSeparatingcharacter(String alias) {
		this(alias, USERDEFINED_SEPARATINGCHARACTER);
	}

	private UserdefinedSeparatingcharacter(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private UserdefinedSeparatingcharacter(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_USERDEFINED_SEPARATINGCHARACTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_USERDEFINED_SEPARATINGCHARACTER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_USERDEFINED_SEPARATINGCHARACTER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_UDSC_SOURCEDOCUMENTID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserdefinedSeparatingcharacter as(String alias) {
		return new UserdefinedSeparatingcharacter(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserdefinedSeparatingcharacter rename(String name) {
		return new UserdefinedSeparatingcharacter(name, null);
	}
}
