/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Catmarepository extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 72068571;

	/**
	 * The singleton instance of <code>CatmaRepository</code>
	 */
	public static final Catmarepository CATMAREPOSITORY = new Catmarepository();

	/**
	 * No further instances allowed
	 */
	private Catmarepository() {
		super("CatmaRepository");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			de.catma.repository.db.jooqgen.catmarepository.tables.Corpus.CORPUS,
			de.catma.repository.db.jooqgen.catmarepository.tables.CorpusSourcedocument.CORPUS_SOURCEDOCUMENT,
			de.catma.repository.db.jooqgen.catmarepository.tables.CorpusStaticmarkupcollection.CORPUS_STATICMARKUPCOLLECTION,
			de.catma.repository.db.jooqgen.catmarepository.tables.CorpusUsermarkupcollection.CORPUS_USERMARKUPCOLLECTION,
			de.catma.repository.db.jooqgen.catmarepository.tables.Property.PROPERTY,
			de.catma.repository.db.jooqgen.catmarepository.tables.Propertydefinition.PROPERTYDEFINITION,
			de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue.PROPERTYDEF_POSSIBLEVALUE,
			de.catma.repository.db.jooqgen.catmarepository.tables.Propertyvalue.PROPERTYVALUE,
			de.catma.repository.db.jooqgen.catmarepository.tables.Sourcedocument.SOURCEDOCUMENT,
			de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupattribute.STATICMARKUPATTRIBUTE,
			de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupcollection.STATICMARKUPCOLLECTION,
			de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupinstance.STATICMARKUPINSTANCE,
			de.catma.repository.db.jooqgen.catmarepository.tables.Tagdefinition.TAGDEFINITION,
			de.catma.repository.db.jooqgen.catmarepository.tables.Taginstance.TAGINSTANCE,
			de.catma.repository.db.jooqgen.catmarepository.tables.Taglibrary.TAGLIBRARY,
			de.catma.repository.db.jooqgen.catmarepository.tables.Tagreference.TAGREFERENCE,
			de.catma.repository.db.jooqgen.catmarepository.tables.Tagsetdefinition.TAGSETDEFINITION,
			de.catma.repository.db.jooqgen.catmarepository.tables.UnseparableCharsequence.UNSEPARABLE_CHARSEQUENCE,
			de.catma.repository.db.jooqgen.catmarepository.tables.User.USER,
			de.catma.repository.db.jooqgen.catmarepository.tables.UserdefinedSeparatingcharacter.USERDEFINED_SEPARATINGCHARACTER,
			de.catma.repository.db.jooqgen.catmarepository.tables.Usermarkupcollection.USERMARKUPCOLLECTION,
			de.catma.repository.db.jooqgen.catmarepository.tables.UserCorpus.USER_CORPUS,
			de.catma.repository.db.jooqgen.catmarepository.tables.UserSourcedocument.USER_SOURCEDOCUMENT,
			de.catma.repository.db.jooqgen.catmarepository.tables.UserStaticmarkupcollection.USER_STATICMARKUPCOLLECTION,
			de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary.USER_TAGLIBRARY,
			de.catma.repository.db.jooqgen.catmarepository.tables.UserUsermarkupcollection.USER_USERMARKUPCOLLECTION);
	}
}
