CREATE  TABLE IF NOT EXISTS `maintenance_sem` (
  `maintenance_semID` INT NOT NULL AUTO_INCREMENT ,
  `type` VARCHAR(45) NOT NULL COMMENT 'CLEANING\nIMPORT\nSYNCH' ,
  `starttime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`maintenance_semID`) )
ENGINE = InnoDB;