package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorpusSourcedocument generated by hbm2java
 */
@Entity
@Table(name = "corpus_sourcedocument", catalog = "CatmaRepository")
public class CorpusSourcedocument implements java.io.Serializable {

	private Integer corpusSourcedocumentId;
	private int corpusId;
	private int sourceDocumentId;

	public CorpusSourcedocument() {
	}

	public CorpusSourcedocument(int corpusId, int sourceDocumentId) {
		this.corpusId = corpusId;
		this.sourceDocumentId = sourceDocumentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "corpus_sourcedocumentID", unique = true, nullable = false)
	public Integer getCorpusSourcedocumentId() {
		return this.corpusSourcedocumentId;
	}

	public void setCorpusSourcedocumentId(Integer corpusSourcedocumentId) {
		this.corpusSourcedocumentId = corpusSourcedocumentId;
	}

	@Column(name = "corpusID", nullable = false)
	public int getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(int corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "sourceDocumentID", nullable = false)
	public int getSourceDocumentId() {
		return this.sourceDocumentId;
	}

	public void setSourceDocumentId(int sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

}
