package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorpusUsermarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "corpus_usermarkupcollection", catalog = "CatmaRepository")
public class CorpusUsermarkupcollection implements java.io.Serializable {

	private Integer corpusUsermarkupcollectionId;
	private int corpusId;
	private int userMarkupCollectionId;

	public CorpusUsermarkupcollection() {
	}

	public CorpusUsermarkupcollection(int corpusId, int userMarkupCollectionId) {
		this.corpusId = corpusId;
		this.userMarkupCollectionId = userMarkupCollectionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "corpus_usermarkupcollectionID", unique = true, nullable = false)
	public Integer getCorpusUsermarkupcollectionId() {
		return this.corpusUsermarkupcollectionId;
	}

	public void setCorpusUsermarkupcollectionId(
			Integer corpusUsermarkupcollectionId) {
		this.corpusUsermarkupcollectionId = corpusUsermarkupcollectionId;
	}

	@Column(name = "corpusID", nullable = false)
	public int getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(int corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "userMarkupCollectionID", nullable = false)
	public int getUserMarkupCollectionId() {
		return this.userMarkupCollectionId;
	}

	public void setUserMarkupCollectionId(int userMarkupCollectionId) {
		this.userMarkupCollectionId = userMarkupCollectionId;
	}

}
