package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Corpus generated by hbm2java
 */
@Entity
@Table(name = "corpus", catalog = "CatmaRepository")
public class DBCorpus implements java.io.Serializable {

	private Integer corpusId;
	private String name;

	public DBCorpus() {
	}

	public DBCorpus(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "corpusID", unique = true, nullable = false)
	public Integer getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(Integer corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
