/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorpusSourcedocument generated by hbm2java
 */
@Entity
@Table(name = "corpus_sourcedocument", catalog = "CatmaRepository")
public class DBCorpusSourceDocument implements java.io.Serializable {

	private Integer corpusSourcedocumentId;
	private int corpusId;
	private DBSourceDocument dbSourceDocument;

	public DBCorpusSourceDocument() {
	}
	
	public DBCorpusSourceDocument(int corpusId,
			DBSourceDocument dbSourceDocument) {
		this.corpusId = corpusId;
		this.dbSourceDocument = dbSourceDocument;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "corpus_sourcedocumentID", unique = true, nullable = false)
	public Integer getCorpusSourcedocumentId() {
		return this.corpusSourcedocumentId;
	}

	public void setCorpusSourcedocumentId(Integer corpusSourcedocumentId) {
		this.corpusSourcedocumentId = corpusSourcedocumentId;
	}

	@Column(name = "corpusID", nullable = false)
	public int getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(int corpusId) {
		this.corpusId = corpusId;
	}


	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "sourceDocumentID", nullable = false)
	public DBSourceDocument getDbSourceDocument() {
		return dbSourceDocument;
	}

	public void setDbSourceDocument(DBSourceDocument dbSourceDocument) {
		this.dbSourceDocument = dbSourceDocument;
	}
}
