/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorpusStaticmarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "corpus_staticmarkupcollection", catalog = "CatmaRepository")
public class DBCorpusStaticMarkupCollection implements java.io.Serializable {

	private Integer corpusStaticmarkupcollectionId;
	private int corpusId;
	private int staticMarkupCollectionId;

	public DBCorpusStaticMarkupCollection() {
	}

	public DBCorpusStaticMarkupCollection(int corpusId,
			int staticMarkupCollectionId) {
		this.corpusId = corpusId;
		this.staticMarkupCollectionId = staticMarkupCollectionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "corpus_staticmarkupcollectionID", unique = true, nullable = false)
	public Integer getCorpusStaticmarkupcollectionId() {
		return this.corpusStaticmarkupcollectionId;
	}

	public void setCorpusStaticmarkupcollectionId(
			Integer corpusStaticmarkupcollectionId) {
		this.corpusStaticmarkupcollectionId = corpusStaticmarkupcollectionId;
	}

	@Column(name = "corpusID", nullable = false)
	public int getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(int corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "staticMarkupCollectionID", nullable = false)
	public int getStaticMarkupCollectionId() {
		return this.staticMarkupCollectionId;
	}

	public void setStaticMarkupCollectionId(int staticMarkupCollectionId) {
		this.staticMarkupCollectionId = staticMarkupCollectionId;
	}

}
