/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorpusUsermarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "corpus_usermarkupcollection", catalog = "CatmaRepository")
public class DBCorpusUserMarkupCollection implements java.io.Serializable {

	private Integer corpusUsermarkupcollectionId;
	private int corpusId;
	private int userMarkupCollectionId;

	public DBCorpusUserMarkupCollection() {
	}

	public DBCorpusUserMarkupCollection(int corpusId, int userMarkupCollectionId) {
		this.corpusId = corpusId;
		this.userMarkupCollectionId = userMarkupCollectionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "corpus_usermarkupcollectionID", unique = true, nullable = false)
	public Integer getCorpusUsermarkupcollectionId() {
		return this.corpusUsermarkupcollectionId;
	}

	public void setCorpusUsermarkupcollectionId(
			Integer corpusUsermarkupcollectionId) {
		this.corpusUsermarkupcollectionId = corpusUsermarkupcollectionId;
	}

	@Column(name = "corpusID", nullable = false)
	public int getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(int corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "userMarkupCollectionID", nullable = false)
	public int getUserMarkupCollectionId() {
		return this.userMarkupCollectionId;
	}

	public void setUserMarkupCollectionId(int userMarkupCollectionId) {
		this.userMarkupCollectionId = userMarkupCollectionId;
	}

}
