package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PropertydefPossiblevalue generated by hbm2java
 */
@Entity
@Table(name = "propertydef_possiblevalue", catalog = "CatmaRepository")
public class DBPropertyDefPossibleValue implements java.io.Serializable {

	private Integer propertydefPossibleValueId;
	private String value;
	private int propertyDefinitionId;

	public DBPropertyDefPossibleValue() {
	}

	public DBPropertyDefPossibleValue(int propertyDefinitionId) {
		this.propertyDefinitionId = propertyDefinitionId;
	}

	public DBPropertyDefPossibleValue(String value, int propertyDefinitionId) {
		this.value = value;
		this.propertyDefinitionId = propertyDefinitionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "propertydefPossibleValueID", unique = true, nullable = false)
	public Integer getPropertydefPossibleValueId() {
		return this.propertydefPossibleValueId;
	}

	public void setPropertydefPossibleValueId(Integer propertydefPossibleValueId) {
		this.propertydefPossibleValueId = propertydefPossibleValueId;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "propertyDefinitionID", nullable = false)
	public int getPropertyDefinitionId() {
		return this.propertyDefinitionId;
	}

	public void setPropertyDefinitionId(int propertyDefinitionId) {
		this.propertyDefinitionId = propertyDefinitionId;
	}

}
