package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Propertydefinition generated by hbm2java
 */
@Entity
@Table(name = "propertydefinition", catalog = "CatmaRepository", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class DBPropertyDefinition implements java.io.Serializable {

	private Integer propertyDefinitionId;
	private byte[] uuid;
	private String name;
	private DBTagDefinition dbTagDefinition;
	private boolean systemproperty;
	private Set<DBPropertyDefPossibleValue> dbPropertyDefPossibleValues = 
			new HashSet<DBPropertyDefPossibleValue>();

	public DBPropertyDefinition() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "propertyDefinitionID", unique = true, nullable = false)
	public Integer getPropertyDefinitionId() {
		return this.propertyDefinitionId;
	}

	public void setPropertyDefinitionId(Integer propertyDefinitionId) {
		this.propertyDefinitionId = propertyDefinitionId;
	}

	@Column(name = "uuid", unique = true, nullable = false)
	public byte[] getUuid() {
		return this.uuid;
	}

	public void setUuid(byte[] uuid) {
		this.uuid = uuid;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tagDefinitionID", nullable = false)
	public DBTagDefinition getDbTagDefinition() {
		return dbTagDefinition;
	}
	
	public void setDbTagDefinition(DBTagDefinition dbTagDefinition) {
		this.dbTagDefinition = dbTagDefinition;
	}

	@Column(name = "systemproperty", nullable = false)
	public boolean isSystemproperty() {
		return this.systemproperty;
	}

	public void setSystemproperty(boolean systemproperty) {
		this.systemproperty = systemproperty;
	}
	
	@OneToMany(mappedBy = "dbPropertyDefinition")
	public Set<DBPropertyDefPossibleValue> getDbPropertyDefPossibleValues() {
		return dbPropertyDefPossibleValues;
	}
	
	public void setDbPropertyDefPossibleValues(
			Set<DBPropertyDefPossibleValue> dbPropertyDefPossibleValues) {
		this.dbPropertyDefPossibleValues = dbPropertyDefPossibleValues;
	}

}
