package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Propertyvalue generated by hbm2java
 */
@Entity
@Table(name = "propertyvalue", catalog = "CatmaRepository")
public class DBPropertyValue implements java.io.Serializable {

	private int propertyValueId;
	private int propertyId;
	private String value;

	public DBPropertyValue() {
	}

	public DBPropertyValue(int propertyValueId, int propertyId) {
		this.propertyValueId = propertyValueId;
		this.propertyId = propertyId;
	}

	public DBPropertyValue(int propertyValueId, int propertyId, String value) {
		this.propertyValueId = propertyValueId;
		this.propertyId = propertyId;
		this.value = value;
	}

	@Id
	@Column(name = "propertyValueID", unique = true, nullable = false)
	public int getPropertyValueId() {
		return this.propertyValueId;
	}

	public void setPropertyValueId(int propertyValueId) {
		this.propertyValueId = propertyValueId;
	}

	@Column(name = "propertyID", nullable = false)
	public int getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(int propertyId) {
		this.propertyId = propertyId;
	}

	@Column(name = "value", length = 1024)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
