/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Propertyvalue generated by hbm2java
 */
@Entity
@Table(name = "propertyvalue", catalog = "CatmaRepository")
public class DBPropertyValue implements java.io.Serializable {

	private int propertyValueId;
	private DBProperty dbProperty;
	private String value;

	public DBPropertyValue() {
	}

	public DBPropertyValue(DBProperty dbProperty, String value) {
		this.dbProperty = dbProperty;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "propertyValueID", unique = true, nullable = false)
	public int getPropertyValueId() {
		return this.propertyValueId;
	}

	public void setPropertyValueId(int propertyValueId) {
		this.propertyValueId = propertyValueId;
	}

	@ManyToOne
	@JoinColumn(name = "propertyID", nullable = false)
	@Cascade({CascadeType.SAVE_UPDATE})
	public DBProperty getDbProperty() {
		return dbProperty;
	}

	public void setDbProperty(DBProperty dbProperty) {
		this.dbProperty = dbProperty;
	}
	
	@Column(name = "value", length = 1024)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
