package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Propertyvalue generated by hbm2java
 */
@Entity
@Table(name = "propertyvalue", catalog = "CatmaRepository")
public class DBPropertyValue implements java.io.Serializable {

	private int propertyValueId;
	private DBProperty dbProperty;
	private String value;

	public DBPropertyValue() {
	}

	public DBPropertyValue(DBProperty dbProperty, String value) {
		this.dbProperty = dbProperty;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "propertyValueID", unique = true, nullable = false)
	public int getPropertyValueId() {
		return this.propertyValueId;
	}

	public void setPropertyValueId(int propertyValueId) {
		this.propertyValueId = propertyValueId;
	}

	@ManyToOne
	@JoinColumn(name = "propertyID", nullable = false)
	@Cascade({CascadeType.SAVE_UPDATE})
	public DBProperty getDbProperty() {
		return dbProperty;
	}

	public void setDbProperty(DBProperty dbProperty) {
		this.dbProperty = dbProperty;
	}
	
	@Column(name = "value", length = 1024)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
