/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staticmarkupattribute generated by hbm2java
 */
@Entity
@Table(name = "staticmarkupattribute", catalog = "CatmaRepository")
public class DBStaticMarkupAttribute implements java.io.Serializable {

	private Integer staticMarkupAttributeId;
	private String name;
	private String value;
	private int staticMarkupInstanceId;

	public DBStaticMarkupAttribute() {
	}

	public DBStaticMarkupAttribute(String name, String value,
			int staticMarkupInstanceId) {
		this.name = name;
		this.value = value;
		this.staticMarkupInstanceId = staticMarkupInstanceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "staticMarkupAttributeID", unique = true, nullable = false)
	public Integer getStaticMarkupAttributeId() {
		return this.staticMarkupAttributeId;
	}

	public void setStaticMarkupAttributeId(Integer staticMarkupAttributeId) {
		this.staticMarkupAttributeId = staticMarkupAttributeId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false, length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "staticMarkupInstanceID", nullable = false)
	public int getStaticMarkupInstanceId() {
		return this.staticMarkupInstanceId;
	}

	public void setStaticMarkupInstanceId(int staticMarkupInstanceId) {
		this.staticMarkupInstanceId = staticMarkupInstanceId;
	}

}
