package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staticmarkupinstance generated by hbm2java
 */
@Entity
@Table(name = "staticmarkupinstance", catalog = "CatmaRepository")
public class DBStaticMarkupInstance implements java.io.Serializable {

	private Integer staticMarkupInstanceId;
	private String name;
	private Integer staticMarkupCollectionId;

	public DBStaticMarkupInstance() {
	}

	public DBStaticMarkupInstance(String name) {
		this.name = name;
	}

	public DBStaticMarkupInstance(String name, Integer staticMarkupCollectionId) {
		this.name = name;
		this.staticMarkupCollectionId = staticMarkupCollectionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "staticMarkupInstanceID", unique = true, nullable = false)
	public Integer getStaticMarkupInstanceId() {
		return this.staticMarkupInstanceId;
	}

	public void setStaticMarkupInstanceId(Integer staticMarkupInstanceId) {
		this.staticMarkupInstanceId = staticMarkupInstanceId;
	}

	@Column(name = "name", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "staticMarkupCollectionID")
	public Integer getStaticMarkupCollectionId() {
		return this.staticMarkupCollectionId;
	}

	public void setStaticMarkupCollectionId(Integer staticMarkupCollectionId) {
		this.staticMarkupCollectionId = staticMarkupCollectionId;
	}

}
