package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staticmarkupattribute generated by hbm2java
 */
@Entity
@Table(name = "staticmarkupattribute", catalog = "CatmaRepository")
public class DBStaticMarkupAttribute implements java.io.Serializable {

	private Integer staticMarkupAttributeId;
	private String name;
	private String value;
	private int staticMarkupInstanceId;

	public DBStaticMarkupAttribute() {
	}

	public DBStaticMarkupAttribute(String name, String value,
			int staticMarkupInstanceId) {
		this.name = name;
		this.value = value;
		this.staticMarkupInstanceId = staticMarkupInstanceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "staticMarkupAttributeID", unique = true, nullable = false)
	public Integer getStaticMarkupAttributeId() {
		return this.staticMarkupAttributeId;
	}

	public void setStaticMarkupAttributeId(Integer staticMarkupAttributeId) {
		this.staticMarkupAttributeId = staticMarkupAttributeId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false, length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "staticMarkupInstanceID", nullable = false)
	public int getStaticMarkupInstanceId() {
		return this.staticMarkupInstanceId;
	}

	public void setStaticMarkupInstanceId(int staticMarkupInstanceId) {
		this.staticMarkupInstanceId = staticMarkupInstanceId;
	}

}
