package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staticmarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "staticmarkupcollection", catalog = "CatmaRepository")
public class DBStaticMarkupCollection implements java.io.Serializable {

	private Integer staticMarkupCollectionId;
	private String name;
	private int sourceDocumentId;

	public DBStaticMarkupCollection() {
	}

	public DBStaticMarkupCollection(String name, int sourceDocumentId) {
		this.name = name;
		this.sourceDocumentId = sourceDocumentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "staticMarkupCollectionID", unique = true, nullable = false)
	public Integer getStaticMarkupCollectionId() {
		return this.staticMarkupCollectionId;
	}

	public void setStaticMarkupCollectionId(Integer staticMarkupCollectionId) {
		this.staticMarkupCollectionId = staticMarkupCollectionId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sourceDocumentID", nullable = false)
	public int getSourceDocumentId() {
		return this.sourceDocumentId;
	}

	public void setSourceDocumentId(int sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

}
