package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tagreference generated by hbm2java
 */
@Entity
@Table(name = "tagreference", catalog = "CatmaRepository")
public class DBTagReference implements java.io.Serializable {

	private Integer tagReferenceId;
	private int characterStart;
	private int characterEnd;
	private int userMarkupCollectionId;
	private int tagInstanceId;

	public DBTagReference() {
	}

	public DBTagReference(int characterStart, int characterEnd,
			int userMarkupCollectionId, int tagInstanceId) {
		this.characterStart = characterStart;
		this.characterEnd = characterEnd;
		this.userMarkupCollectionId = userMarkupCollectionId;
		this.tagInstanceId = tagInstanceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tagReferenceID", unique = true, nullable = false)
	public Integer getTagReferenceId() {
		return this.tagReferenceId;
	}

	public void setTagReferenceId(Integer tagReferenceId) {
		this.tagReferenceId = tagReferenceId;
	}

	@Column(name = "characterStart", nullable = false)
	public int getCharacterStart() {
		return this.characterStart;
	}

	public void setCharacterStart(int characterStart) {
		this.characterStart = characterStart;
	}

	@Column(name = "characterEnd", nullable = false)
	public int getCharacterEnd() {
		return this.characterEnd;
	}

	public void setCharacterEnd(int characterEnd) {
		this.characterEnd = characterEnd;
	}

	@Column(name = "userMarkupCollectionID", nullable = false)
	public int getUserMarkupCollectionId() {
		return this.userMarkupCollectionId;
	}

	public void setUserMarkupCollectionId(int userMarkupCollectionId) {
		this.userMarkupCollectionId = userMarkupCollectionId;
	}

	@Column(name = "tagInstanceID", nullable = false)
	public int getTagInstanceId() {
		return this.tagInstanceId;
	}

	public void setTagInstanceId(int tagInstanceId) {
		this.tagInstanceId = tagInstanceId;
	}

}
