package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Tagdefinition generated by hbm2java
 */
@Entity
@Table(name = "tagdefinition", catalog = "CatmaRepository", uniqueConstraints = @UniqueConstraint(columnNames = {
		"uuid", "version" }))
public class DBTagDefinition implements java.io.Serializable {

	private Integer tagDefinitionId;
	private Date version;
	private byte[] uuid;
	private String name;
	private DBTagsetDefinition dbTagsetDefinition;
	private Integer parentId;
	private byte[] parentUuid;
	
	private Set<DBPropertyDefinition> dbPropertyDefinitions = 
			new HashSet<DBPropertyDefinition>();
	
	public DBTagDefinition() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tagDefinitionID", unique = true, nullable = false)
	public Integer getTagDefinitionId() {
		return this.tagDefinitionId;
	}

	public void setTagDefinitionId(Integer tagDefinitionId) {
		this.tagDefinitionId = tagDefinitionId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", nullable = false, length = 19)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "uuid", nullable = false)
	public byte[] getUuid() {
		return this.uuid;
	}

	public void setUuid(byte[] uuid) {
		this.uuid = uuid;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tagsetDefinitionID", nullable = false)
	public DBTagsetDefinition getDbTagsetDefinition() {
		return dbTagsetDefinition;
	}
	
	public void setDbTagsetDefinition(DBTagsetDefinition dbTagsetDefinition) {
		this.dbTagsetDefinition = dbTagsetDefinition;
	}

	@Column(name = "parentID")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
	
	@Column(name = "parentUuid", nullable = false)
	public byte[] getParentUuid() {
		return this.parentUuid;
	}

	public void setParentUuid(byte[] parentUuid) {
		this.parentUuid = parentUuid;
	}

	@OneToMany(mappedBy ="dbTagDefinition")
	public Set<DBPropertyDefinition> getDbPropertyDefinitions() {
		return dbPropertyDefinitions;
	}
	
	public void setDbPropertyDefinitions(
			Set<DBPropertyDefinition> dbPropertyDefinitions) {
		this.dbPropertyDefinitions = dbPropertyDefinitions;
	}
}
