package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Taginstance generated by hbm2java
 */
@Entity
@Table(name = "taginstance", catalog = "CatmaRepository", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class DBTagInstance implements java.io.Serializable {

	private Integer tagInstanceId;
	private byte[] uuid;
	private int tagDefinitionId;

	public DBTagInstance() {
	}

	public DBTagInstance(byte[] uuid, int tagDefinitionId) {
		this.uuid = uuid;
		this.tagDefinitionId = tagDefinitionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tagInstanceID", unique = true, nullable = false)
	public Integer getTagInstanceId() {
		return this.tagInstanceId;
	}

	public void setTagInstanceId(Integer tagInstanceId) {
		this.tagInstanceId = tagInstanceId;
	}

	@Column(name = "uuid", unique = true, nullable = false)
	public byte[] getUuid() {
		return this.uuid;
	}

	public void setUuid(byte[] uuid) {
		this.uuid = uuid;
	}

	@Column(name = "tagDefinitionID", nullable = false)
	public int getTagDefinitionId() {
		return this.tagDefinitionId;
	}

	public void setTagDefinitionId(int tagDefinitionId) {
		this.tagDefinitionId = tagDefinitionId;
	}

}
