package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Tagsetdefinition generated by hbm2java
 */
@Entity
@Table(name = "tagsetdefinition", catalog = "CatmaRepository", uniqueConstraints = @UniqueConstraint(columnNames = {
		"uuid", "version" }))
public class DBTagsetDefinition implements java.io.Serializable {

	private Integer tagsetDefinitionId;
	private Date version;
	private byte[] uuid;
	private String name;
	private int tagLibraryId;

	public DBTagsetDefinition() {
	}

	public DBTagsetDefinition(byte[] uuid, String name, int tagLibraryId) {
		this.uuid = uuid;
		this.name = name;
		this.tagLibraryId = tagLibraryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tagsetDefinitionID", unique = true, nullable = false)
	public Integer getTagsetDefinitionId() {
		return this.tagsetDefinitionId;
	}

	public void setTagsetDefinitionId(Integer tagsetDefinitionId) {
		this.tagsetDefinitionId = tagsetDefinitionId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", nullable = false, length = 19)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "uuid", nullable = false)
	public byte[] getUuid() {
		return this.uuid;
	}

	public void setUuid(byte[] uuid) {
		this.uuid = uuid;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tagLibraryID", nullable = false)
	public int getTagLibraryId() {
		return this.tagLibraryId;
	}

	public void setTagLibraryId(int tagLibraryId) {
		this.tagLibraryId = tagLibraryId;
	}

}
