/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnseparableCharsequence generated by hbm2java
 */
@Entity
@Table(name = "unseparable_charsequence", catalog = "CatmaRepository")
public class DBUnseparableCharsequence implements java.io.Serializable {

	private Integer uscId;
	private String charsequence;

	public DBUnseparableCharsequence() {
	}

	public DBUnseparableCharsequence(String charsequence) {
		this.charsequence = charsequence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "uscID", unique = true, nullable = false)
	public Integer getUscId() {
		return this.uscId;
	}

	public void setUscId(Integer uscId) {
		this.uscId = uscId;
	}

	@Column(name = "charsequence", nullable = false, length = 45)
	public String getCharsequence() {
		return this.charsequence;
	}

	public void setCharsequence(String charsequence) {
		this.charsequence = charsequence;
	}
}
