package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserSourcedocument generated by hbm2java
 */
@Entity
@Table(name = "user_sourcedocument", catalog = "CatmaRepository")
public class DBUserSourceDocument implements java.io.Serializable {

	private Integer userSourcedocumentId;
	private int userId;
	private int sourceDocumentId;
	private int accessMode;
	private boolean owner;

	public DBUserSourceDocument() {
	}

	public DBUserSourceDocument(int userId, int sourceDocumentId, int accessMode,
			boolean owner) {
		this.userId = userId;
		this.sourceDocumentId = sourceDocumentId;
		this.accessMode = accessMode;
		this.owner = owner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_sourcedocumentID", unique = true, nullable = false)
	public Integer getUserSourcedocumentId() {
		return this.userSourcedocumentId;
	}

	public void setUserSourcedocumentId(Integer userSourcedocumentId) {
		this.userSourcedocumentId = userSourcedocumentId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "sourceDocumentID", nullable = false)
	public int getSourceDocumentId() {
		return this.sourceDocumentId;
	}

	public void setSourceDocumentId(int sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
