package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserCorpus generated by hbm2java
 */
@Entity
@Table(name = "user_corpus", catalog = "CatmaRepository")
public class DBUserCorpus implements java.io.Serializable {

	private Integer userCorpusId;
	private int userId;
	private int corpusId;
	private int accessMode;
	private boolean owner;

	public DBUserCorpus() {
	}

	public DBUserCorpus(int userId, int corpusId, int accessMode, boolean owner) {
		this.userId = userId;
		this.corpusId = corpusId;
		this.accessMode = accessMode;
		this.owner = owner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_corpusID", unique = true, nullable = false)
	public Integer getUserCorpusId() {
		return this.userCorpusId;
	}

	public void setUserCorpusId(Integer userCorpusId) {
		this.userCorpusId = userCorpusId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "corpusID", nullable = false)
	public int getCorpusId() {
		return this.corpusId;
	}

	public void setCorpusId(int corpusId) {
		this.corpusId = corpusId;
	}

	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
