package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserUsermarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "user_usermarkupcollection", catalog = "CatmaRepository")
public class DBUserUserMarkupCollection implements java.io.Serializable {

	private Integer userUsermarkupcollectioId;
	private int userId;
	private int userMarkupCollectionId;
	private int accessMode;
	private boolean owner;

	public DBUserUserMarkupCollection() {
	}

	public DBUserUserMarkupCollection(int userId, int userMarkupCollectionId,
			int accessMode, boolean owner) {
		this.userId = userId;
		this.userMarkupCollectionId = userMarkupCollectionId;
		this.accessMode = accessMode;
		this.owner = owner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_usermarkupcollectioID", unique = true, nullable = false)
	public Integer getUserUsermarkupcollectioId() {
		return this.userUsermarkupcollectioId;
	}

	public void setUserUsermarkupcollectioId(Integer userUsermarkupcollectioId) {
		this.userUsermarkupcollectioId = userUsermarkupcollectioId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userMarkupCollectionID", nullable = false)
	public int getUserMarkupCollectionId() {
		return this.userMarkupCollectionId;
	}

	public void setUserMarkupCollectionId(int userMarkupCollectionId) {
		this.userMarkupCollectionId = userMarkupCollectionId;
	}

	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
