package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserTaglibrary generated by hbm2java
 */
@Entity
@Table(name = "user_taglibrary", catalog = "CatmaRepository")
public class DBUserTagLibrary implements java.io.Serializable {

	private Integer userTagLibraryId;
	private int userId;
	private int tagLibraryId;
	private int accessMode;
	private boolean owner;

	public DBUserTagLibrary() {
	}

	public DBUserTagLibrary(int userId, int tagLibraryId, int accessMode,
			boolean owner) {
		this.userId = userId;
		this.tagLibraryId = tagLibraryId;
		this.accessMode = accessMode;
		this.owner = owner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_tagLibraryID", unique = true, nullable = false)
	public Integer getUserTagLibraryId() {
		return this.userTagLibraryId;
	}

	public void setUserTagLibraryId(Integer userTagLibraryId) {
		this.userTagLibraryId = userTagLibraryId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "tagLibraryID", nullable = false)
	public int getTagLibraryId() {
		return this.tagLibraryId;
	}

	public void setTagLibraryId(int tagLibraryId) {
		this.tagLibraryId = tagLibraryId;
	}

	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
