/*   
 *   CATMA Computer Aided Text Markup and Analysis
 *   
 *   Copyright (C) 2009-2013  University Of Hamburg
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserStaticmarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "user_staticmarkupcollection", catalog = "CatmaRepository")
public class DBUserStaticMarkupCollection implements java.io.Serializable {

	private Integer userStaticmarkupcollectionId;
	private int userId;
	private int staticMarkupCollectionId;
	private int accessMode;
	private boolean owner;

	public DBUserStaticMarkupCollection() {
	}

	public DBUserStaticMarkupCollection(int userId, int staticMarkupCollectionId,
			int accessMode, boolean owner) {
		this.userId = userId;
		this.staticMarkupCollectionId = staticMarkupCollectionId;
		this.accessMode = accessMode;
		this.owner = owner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_staticmarkupcollectionID", unique = true, nullable = false)
	public Integer getUserStaticmarkupcollectionId() {
		return this.userStaticmarkupcollectionId;
	}

	public void setUserStaticmarkupcollectionId(
			Integer userStaticmarkupcollectionId) {
		this.userStaticmarkupcollectionId = userStaticmarkupcollectionId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "staticMarkupCollectionID", nullable = false)
	public int getStaticMarkupCollectionId() {
		return this.staticMarkupCollectionId;
	}

	public void setStaticMarkupCollectionId(int staticMarkupCollectionId) {
		this.staticMarkupCollectionId = staticMarkupCollectionId;
	}

	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
