package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserCorpus generated by hbm2java
 */
@Entity
@Table(name = "user_corpus", catalog = "CatmaRepository")
public class DBUserCorpus implements java.io.Serializable {

	private Integer userCorpusId;
	private DBUser dbUser;
	private DBCorpus dbCorpus;
	private int accessMode;
	private boolean owner;

	public DBUserCorpus() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_corpusID", unique = true, nullable = false)
	public Integer getUserCorpusId() {
		return this.userCorpusId;
	}

	public void setUserCorpusId(Integer userCorpusId) {
		this.userCorpusId = userCorpusId;
	}

	@ManyToOne
	@JoinColumn(name = "userID", nullable = false)
	public DBUser getDbUser() {
		return dbUser;
	}

	public void setDbUser(DBUser dbUser) {
		this.dbUser = dbUser;
	}

	@ManyToOne
	@JoinColumn(name = "corpusID", nullable = false)
	public DBCorpus getDbCorpus() {
		return dbCorpus;
	}

	public void setDbCorpus(DBCorpus dbCorpus) {
		this.dbCorpus = dbCorpus;
	}
	
	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
