package de.catma.repository.db.model;

// Generated 23.05.2012 12:54:30 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import de.catma.document.repository.AccessMode;

/**
 * UserSourcedocument generated by hbm2java
 */
@Entity
@Table(name = "user_sourcedocument", catalog = "CatmaRepository")
public class DBUserSourceDocument implements java.io.Serializable {

	private Integer userSourcedocumentId;
	private DBUser dbUser;
	private DBSourceDocument dbSourceDocument;
	private int accessMode;
	private boolean owner;

	public DBUserSourceDocument() {
	}

	public DBUserSourceDocument(DBUser dbUser,
			DBSourceDocument dbSourceDocument) {
		this.dbUser = dbUser;
		this.dbSourceDocument = dbSourceDocument;
		this.accessMode = AccessMode.WRITE.getNumericRepresentation();
		this.owner = true;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_sourcedocumentID", unique = true, nullable = false)
	public Integer getUserSourcedocumentId() {
		return this.userSourcedocumentId;
	}

	public void setUserSourcedocumentId(Integer userSourcedocumentId) {
		this.userSourcedocumentId = userSourcedocumentId;
	}

	@ManyToOne
	@JoinColumn(name = "userID", nullable = false)
	public DBUser getDbUser() {
		return dbUser;
	}

	public void setDbUser(DBUser dbUser) {
		this.dbUser = dbUser;
	}

	@ManyToOne
	@JoinColumn(name = "sourceDocumentID", nullable = false)
	public DBSourceDocument getDbSourceDocument() {
		return dbSourceDocument;
	}
	
	public void setDbSourceDocument(DBSourceDocument dbSourceDocument) {
		this.dbSourceDocument = dbSourceDocument;
	}
	
	@Column(name = "accessMode", nullable = false)
	public int getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(int accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "owner", nullable = false)
	public boolean isOwner() {
		return this.owner;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

}
