package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import de.catma.document.ContentInfoSet;
import de.catma.document.standoffmarkup.usermarkup.IUserMarkupCollection;
import de.catma.document.standoffmarkup.usermarkup.TagReference;
import de.catma.document.standoffmarkup.usermarkup.UserMarkupCollection;
import de.catma.tag.ITagLibrary;
import de.catma.tag.TagDefinition;
import de.catma.tag.TagInstance;
import de.catma.tag.TagsetDefinition;

/**
 * Usermarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "usermarkupcollection", catalog = "CatmaRepository")
public class DBUserMarkupCollection implements java.io.Serializable, IUserMarkupCollection {

	private Integer usermarkupCollectionId;
	private int sourceDocumentId;
	private IUserMarkupCollection userMarkupCollectionDelegate;
	private Set<DBUserUserMarkupCollection> dbUserUserMarkupCollections = 
			new HashSet<DBUserUserMarkupCollection>();
	private Set<DBTagReference> dbTagReferences = new HashSet<DBTagReference>();
	
	public DBUserMarkupCollection() {
		userMarkupCollectionDelegate =
				new UserMarkupCollection(
						null, // gets filled out by setUsermarkupCollectionId
						new ContentInfoSet(),
						new DBTagLibrary(),
						new ArrayList<TagReference>());
	}
	
	public DBUserMarkupCollection(int sourceDocumentId, String title) {
		this.sourceDocumentId = sourceDocumentId;
		userMarkupCollectionDelegate =
				new UserMarkupCollection(
						null, // gets filled out by setUsermarkupCollectionId
						new ContentInfoSet(title),
						new DBTagLibrary(title, false),
						new ArrayList<TagReference>());
	}
	
	public DBUserMarkupCollection(
			int sourceDocumentId,
			IUserMarkupCollection userMarkupCollectionDelegate) {
		this.sourceDocumentId = sourceDocumentId;
		this.userMarkupCollectionDelegate = userMarkupCollectionDelegate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "usermarkupCollectionID", unique = true, nullable = false)
	public Integer getUsermarkupCollectionId() {
		return this.usermarkupCollectionId;
	}

	public void setUsermarkupCollectionId(Integer usermarkupCollectionId) {
		this.usermarkupCollectionId = usermarkupCollectionId;
		userMarkupCollectionDelegate.setId(usermarkupCollectionId.toString());
	}

	@Column(name = "title", length = 300)
	public String getTitle() {
		return userMarkupCollectionDelegate.getContentInfoSet().getTitle();
	}

	public void setTitle(String title) {
		userMarkupCollectionDelegate.getContentInfoSet().setTitle(title);
	}

	@Column(name = "publisher", length = 300)
	public String getPublisher() {
		return userMarkupCollectionDelegate.getContentInfoSet().getPublisher();
	}

	public void setPublisher(String publisher) {
		userMarkupCollectionDelegate.getContentInfoSet().setPublisher(publisher);
	}

	@Column(name = "author", length = 300)
	public String getAuthor() {
		return userMarkupCollectionDelegate.getContentInfoSet().getAuthor();
	}

	public void setAuthor(String author) {
		userMarkupCollectionDelegate.getContentInfoSet().setAuthor(author);
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return userMarkupCollectionDelegate.getContentInfoSet().getDescription();
	}

	public void setDescription(String description) {
		userMarkupCollectionDelegate.getContentInfoSet().setDescription(description);
	}

	@Column(name = "sourceDocumentID", nullable = false)
	public int getSourceDocumentId() {
		return this.sourceDocumentId;
	}

	public void setSourceDocumentId(int sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

	@OneToOne
	@Cascade({CascadeType.DELETE, CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "tagLibraryID", nullable = false)
	public DBTagLibrary getTagLibrary() {
		return (DBTagLibrary)userMarkupCollectionDelegate.getTagLibrary();
	}
	
	public void setTagLibrary(ITagLibrary tagLibrary) {
		userMarkupCollectionDelegate.setTagLibrary(tagLibrary);
	}
	
	@OneToMany(mappedBy = "dbUserMarkupCollection")
	@Cascade({CascadeType.DELETE, CascadeType.SAVE_UPDATE})
	public Set<DBUserUserMarkupCollection> getDbUserUserMarkupCollections() {
		return dbUserUserMarkupCollections;
	}
	
	public void setDbUserUserMarkupCollections(
			Set<DBUserUserMarkupCollection> dbUserUserMarkupCollections) {
		this.dbUserUserMarkupCollections = dbUserUserMarkupCollections;
	}
	
	@OneToMany(mappedBy = "dbUserMarkupCollection")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public Set<DBTagReference> getDbTagReferences() {
		return dbTagReferences;
	}
	
	public void setDbTagReferences(Set<DBTagReference> dbTagReferences) {
		this.dbTagReferences = dbTagReferences;
	}
	
	@Transient
	public List<TagReference> getTagReferences() {
		return userMarkupCollectionDelegate.getTagReferences();
	}

	@Transient
	public List<TagReference> getTagReferences(TagDefinition tagDefinition) {
		return userMarkupCollectionDelegate.getTagReferences(tagDefinition);
	}

	@Transient
	public List<TagReference> getTagReferences(TagDefinition tagDefinition,
			boolean withChildReferences) {
		return userMarkupCollectionDelegate.getTagReferences(
				tagDefinition, withChildReferences);
	}

	@Transient
	public Set<String> getChildIDs(TagDefinition tagDefinition) {
		return userMarkupCollectionDelegate.getChildIDs(tagDefinition);
	}

	@Transient
	public List<TagDefinition> getChildren(TagDefinition tagDefinition) {
		return userMarkupCollectionDelegate.getChildren(tagDefinition);
	}

	public void update(TagsetDefinition tagsetDefinition) {
		userMarkupCollectionDelegate.update(tagsetDefinition);
	}

	public void addTagReferences(List<TagReference> tagReferences) {
		userMarkupCollectionDelegate.addTagReferences(tagReferences);
	}

	
	
	public void addTagReference(TagReference tagReference) {
		userMarkupCollectionDelegate.addTagReference(tagReference);
	}

	@Transient
	public String getId() {
		return userMarkupCollectionDelegate.getId();
	}

	@Transient
	public String getName() {
		return userMarkupCollectionDelegate.getName();
	}

	@Transient
	public ContentInfoSet getContentInfoSet() {
		return userMarkupCollectionDelegate.getContentInfoSet();
	}
	
	@Transient
	public boolean isEmpty() {
		return userMarkupCollectionDelegate.isEmpty();
	}

	public String toString() {
		return userMarkupCollectionDelegate.toString();
	}

	public boolean hasAccess(DBUser dbUser) {
		for (DBUserUserMarkupCollection uumc : getDbUserUserMarkupCollections()) {
			if (uumc.getDbUser().getUserId().equals(dbUser.getUserId())) {
				return true;
			}
		}
		return false;
	}

	public void setId(String id) {
		userMarkupCollectionDelegate.setId(id);
	}

	public void synchronizeTagInstances(boolean withUserDefinedPropertyValues) {
		userMarkupCollectionDelegate
				.synchronizeTagInstances(withUserDefinedPropertyValues);
	}
	
	@Transient
	public Set<TagReference> getTagReferences(TagInstance ti) {
		return userMarkupCollectionDelegate.getTagReferences(ti);
	}
	
	@Transient
	public IUserMarkupCollection getUserMarkupCollectionDelegate() {
		return userMarkupCollectionDelegate;
	}
	
	public void setUserMarkupCollectionDelegate(
			IUserMarkupCollection userMarkupCollectionDelegate) {
		this.userMarkupCollectionDelegate = userMarkupCollectionDelegate;
	}

	@Transient
	public Set<TagReference> getTagReferences(String tagInstanceID) {
		return userMarkupCollectionDelegate.getTagReferences(tagInstanceID);
	}

	public boolean hasTagInstance(String instanceID) {
		return userMarkupCollectionDelegate.hasTagInstance(instanceID);
	}

	public void removeTagReferences(Set<TagReference> tagReferences) {
		userMarkupCollectionDelegate.removeTagReferences(tagReferences);
	}

	
}