package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usermarkupcollection generated by hbm2java
 */
@Entity
@Table(name = "usermarkupcollection", catalog = "CatmaRepository")
public class DBUserMarkupCollection implements java.io.Serializable {

	private Integer usermarkupCollectionId;
	private String title;
	private String publisher;
	private String author;
	private String description;
	private int sourceDocumentId;
	private int tagLibraryId;

	public DBUserMarkupCollection() {
	}

	public DBUserMarkupCollection(int sourceDocumentId, int tagLibraryId) {
		this.sourceDocumentId = sourceDocumentId;
		this.tagLibraryId = tagLibraryId;
	}

	public DBUserMarkupCollection(String title, String publisher, String author,
			String description, int sourceDocumentId, int tagLibraryId) {
		this.title = title;
		this.publisher = publisher;
		this.author = author;
		this.description = description;
		this.sourceDocumentId = sourceDocumentId;
		this.tagLibraryId = tagLibraryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "usermarkupCollectionID", unique = true, nullable = false)
	public Integer getUsermarkupCollectionId() {
		return this.usermarkupCollectionId;
	}

	public void setUsermarkupCollectionId(Integer usermarkupCollectionId) {
		this.usermarkupCollectionId = usermarkupCollectionId;
	}

	@Column(name = "title", length = 300)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "publisher", length = 300)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "author", length = 300)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sourceDocumentID", nullable = false)
	public int getSourceDocumentId() {
		return this.sourceDocumentId;
	}

	public void setSourceDocumentId(int sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

	@Column(name = "tagLibraryID", nullable = false)
	public int getTagLibraryId() {
		return this.tagLibraryId;
	}

	public void setTagLibraryId(int tagLibraryId) {
		this.tagLibraryId = tagLibraryId;
	}

}
