package de.catma.repository.db.model;

// Generated 22.05.2012 21:58:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserdefinedSeparatingcharacter generated by hbm2java
 */
@Entity
@Table(name = "userdefined_separatingcharacter", catalog = "CatmaRepository")
public class DBUserDefinedSeparatingCharacter implements java.io.Serializable {

	private Integer udscId;
	private String character;
	private int sourceDocumentId;

	public DBUserDefinedSeparatingCharacter() {
	}

	public DBUserDefinedSeparatingCharacter(String character, int sourceDocumentId) {
		this.character = character;
		this.sourceDocumentId = sourceDocumentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "udscID", unique = true, nullable = false)
	public Integer getUdscId() {
		return this.udscId;
	}

	public void setUdscId(Integer udscId) {
		this.udscId = udscId;
	}

	@Column(name = "character", nullable = false, length = 5)
	public String getCharacter() {
		return this.character;
	}

	public void setCharacter(String character) {
		this.character = character;
	}

	@Column(name = "sourceDocumentID", nullable = false)
	public int getSourceDocumentId() {
		return this.sourceDocumentId;
	}

	public void setSourceDocumentId(int sourceDocumentId) {
		this.sourceDocumentId = sourceDocumentId;
	}

}
