/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpusStaticmarkupcollection extends TableImpl<Record> {

	private static final long serialVersionUID = -723640895;

	/**
	 * The reference instance of <code>catmarepository.corpus_staticmarkupcollection</code>
	 */
	public static final CorpusStaticmarkupcollection CORPUS_STATICMARKUPCOLLECTION = new CorpusStaticmarkupcollection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.corpus_staticmarkupcollection.corpus_staticmarkupcollectionID</code>.
	 */
	public final TableField<Record, Integer> CORPUS_STATICMARKUPCOLLECTIONID = createField("corpus_staticmarkupcollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.corpus_staticmarkupcollection.corpusID</code>.
	 */
	public final TableField<Record, Integer> CORPUSID = createField("corpusID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.corpus_staticmarkupcollection.staticMarkupCollectionID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPCOLLECTIONID = createField("staticMarkupCollectionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.corpus_staticmarkupcollection</code> table reference
	 */
	public CorpusStaticmarkupcollection() {
		this("corpus_staticmarkupcollection", null);
	}

	/**
	 * Create an aliased <code>catmarepository.corpus_staticmarkupcollection</code> table reference
	 */
	public CorpusStaticmarkupcollection(String alias) {
		this(alias, CORPUS_STATICMARKUPCOLLECTION);
	}

	private CorpusStaticmarkupcollection(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private CorpusStaticmarkupcollection(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_CORPUS_STATICMARKUPCOLLECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_CORPUS_STATICMARKUPCOLLECTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_CORPUS_STATICMARKUPCOLLECTION_PRIMARY, Keys.KEY_CORPUS_STATICMARKUPCOLLECTION_UK_CORPUSSMC_CORPUSID_SMCID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_CORPUSSMC_CORPUSID, Keys.FK_CORPUSSMC_STATICMARKUPCOLLECTIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CorpusStaticmarkupcollection as(String alias) {
		return new CorpusStaticmarkupcollection(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CorpusStaticmarkupcollection rename(String name) {
		return new CorpusStaticmarkupcollection(name, null);
	}
}
