/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Propertydefinition extends TableImpl<Record> {

	private static final long serialVersionUID = -444132070;

	/**
	 * The reference instance of <code>catmarepository.propertydefinition</code>
	 */
	public static final Propertydefinition PROPERTYDEFINITION = new Propertydefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.propertydefinition.propertyDefinitionID</code>.
	 */
	public final TableField<Record, Integer> PROPERTYDEFINITIONID = createField("propertyDefinitionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.propertydefinition.uuid</code>.
	 */
	public final TableField<Record, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.propertydefinition.name</code>.
	 */
	public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.propertydefinition.tagDefinitionID</code>.
	 */
	public final TableField<Record, Integer> TAGDEFINITIONID = createField("tagDefinitionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.propertydefinition.systemproperty</code>.
	 */
	public final TableField<Record, Byte> SYSTEMPROPERTY = createField("systemproperty", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.propertydefinition</code> table reference
	 */
	public Propertydefinition() {
		this("propertydefinition", null);
	}

	/**
	 * Create an aliased <code>catmarepository.propertydefinition</code> table reference
	 */
	public Propertydefinition(String alias) {
		this(alias, PROPERTYDEFINITION);
	}

	private Propertydefinition(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Propertydefinition(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_PROPERTYDEFINITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_PROPERTYDEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PROPERTYDEFINITION_PRIMARY, Keys.KEY_PROPERTYDEFINITION_UK_PD_UUID_TDEF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_PD_TAGDEFINITIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Propertydefinition as(String alias) {
		return new Propertydefinition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Propertydefinition rename(String name) {
		return new Propertydefinition(name, null);
	}
}
