/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermission extends TableImpl<Record> {

	private static final long serialVersionUID = -1924240702;

	/**
	 * The reference instance of <code>catmarepository.role_permission</code>
	 */
	public static final RolePermission ROLE_PERMISSION = new RolePermission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.role_permission.role_permissionID</code>.
	 */
	public final TableField<Record, Integer> ROLE_PERMISSIONID = createField("role_permissionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.role_permission.roleID</code>.
	 */
	public final TableField<Record, Integer> ROLEID = createField("roleID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.role_permission.permissionID</code>.
	 */
	public final TableField<Record, Integer> PERMISSIONID = createField("permissionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.role_permission</code> table reference
	 */
	public RolePermission() {
		this("role_permission", null);
	}

	/**
	 * Create an aliased <code>catmarepository.role_permission</code> table reference
	 */
	public RolePermission(String alias) {
		this(alias, ROLE_PERMISSION);
	}

	private RolePermission(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private RolePermission(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_ROLE_PERMISSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_ROLE_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ROLE_PERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_ROLE_PERM_ROLEID, Keys.FK_ROLE_PERM_PERMISSIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RolePermission as(String alias) {
		return new RolePermission(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RolePermission rename(String name) {
		return new RolePermission(name, null);
	}
}
