/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staticmarkupinstance extends TableImpl<Record> {

	private static final long serialVersionUID = -253447222;

	/**
	 * The reference instance of <code>catmarepository.staticmarkupinstance</code>
	 */
	public static final Staticmarkupinstance STATICMARKUPINSTANCE = new Staticmarkupinstance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.staticmarkupinstance.staticMarkupInstanceID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPINSTANCEID = createField("staticMarkupInstanceID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupinstance.name</code>.
	 */
	public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupinstance.staticMarkupCollectionID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPCOLLECTIONID = createField("staticMarkupCollectionID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>catmarepository.staticmarkupinstance</code> table reference
	 */
	public Staticmarkupinstance() {
		this("staticmarkupinstance", null);
	}

	/**
	 * Create an aliased <code>catmarepository.staticmarkupinstance</code> table reference
	 */
	public Staticmarkupinstance(String alias) {
		this(alias, STATICMARKUPINSTANCE);
	}

	private Staticmarkupinstance(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Staticmarkupinstance(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_STATICMARKUPINSTANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_STATICMARKUPINSTANCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_STATICMARKUPINSTANCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_STATICMI_STATICMARKUPCOLLECTIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Staticmarkupinstance as(String alias) {
		return new Staticmarkupinstance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Staticmarkupinstance rename(String name) {
		return new Staticmarkupinstance(name, null);
	}
}
