/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staticmarkupattribute extends TableImpl<Record> {

	private static final long serialVersionUID = -751429046;

	/**
	 * The reference instance of <code>catmarepository.staticmarkupattribute</code>
	 */
	public static final Staticmarkupattribute STATICMARKUPATTRIBUTE = new Staticmarkupattribute();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.staticmarkupattribute.staticMarkupAttributeID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPATTRIBUTEID = createField("staticMarkupAttributeID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupattribute.name</code>.
	 */
	public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupattribute.value</code>.
	 */
	public final TableField<Record, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.staticmarkupattribute.staticMarkupInstanceID</code>.
	 */
	public final TableField<Record, Integer> STATICMARKUPINSTANCEID = createField("staticMarkupInstanceID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.staticmarkupattribute</code> table reference
	 */
	public Staticmarkupattribute() {
		this("staticmarkupattribute", null);
	}

	/**
	 * Create an aliased <code>catmarepository.staticmarkupattribute</code> table reference
	 */
	public Staticmarkupattribute(String alias) {
		this(alias, STATICMARKUPATTRIBUTE);
	}

	private Staticmarkupattribute(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Staticmarkupattribute(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_STATICMARKUPATTRIBUTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_STATICMARKUPATTRIBUTE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_STATICMARKUPATTRIBUTE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_STATICA_STATICMARKUPINSTANCEID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Staticmarkupattribute as(String alias) {
		return new Staticmarkupattribute(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Staticmarkupattribute rename(String name) {
		return new Staticmarkupattribute(name, null);
	}
}
