/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository.tables;


import de.catma.repository.db.jooqgen.catmarepository.Catmarepository;
import de.catma.repository.db.jooqgen.catmarepository.Keys;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagsetdefinition extends TableImpl<Record> {

	private static final long serialVersionUID = 442656465;

	/**
	 * The reference instance of <code>catmarepository.tagsetdefinition</code>
	 */
	public static final Tagsetdefinition TAGSETDEFINITION = new Tagsetdefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>catmarepository.tagsetdefinition.tagsetDefinitionID</code>.
	 */
	public final TableField<Record, Integer> TAGSETDEFINITIONID = createField("tagsetDefinitionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.tagsetdefinition.uuid</code>.
	 */
	public final TableField<Record, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.tagsetdefinition.version</code>.
	 */
	public final TableField<Record, Timestamp> VERSION = createField("version", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>catmarepository.tagsetdefinition.name</code>.
	 */
	public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>catmarepository.tagsetdefinition.tagLibraryID</code>.
	 */
	public final TableField<Record, Integer> TAGLIBRARYID = createField("tagLibraryID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>catmarepository.tagsetdefinition</code> table reference
	 */
	public Tagsetdefinition() {
		this("tagsetdefinition", null);
	}

	/**
	 * Create an aliased <code>catmarepository.tagsetdefinition</code> table reference
	 */
	public Tagsetdefinition(String alias) {
		this(alias, TAGSETDEFINITION);
	}

	private Tagsetdefinition(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Tagsetdefinition(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Catmarepository.CATMAREPOSITORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_TAGSETDEFINITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.KEY_TAGSETDEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.KEY_TAGSETDEFINITION_PRIMARY, Keys.KEY_TAGSETDEFINITION_UK_TSDEF_TLIB_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK_TSDEF_TAGLIBRARYID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Tagsetdefinition as(String alias) {
		return new Tagsetdefinition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Tagsetdefinition rename(String name) {
		return new Tagsetdefinition(name, null);
	}
}
