/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository;


import de.catma.repository.db.jooqgen.catmarepository.tables.Corpus;
import de.catma.repository.db.jooqgen.catmarepository.tables.CorpusSourcedocument;
import de.catma.repository.db.jooqgen.catmarepository.tables.CorpusStaticmarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.CorpusUsermarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem;
import de.catma.repository.db.jooqgen.catmarepository.tables.Permission;
import de.catma.repository.db.jooqgen.catmarepository.tables.Property;
import de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue;
import de.catma.repository.db.jooqgen.catmarepository.tables.Propertydefinition;
import de.catma.repository.db.jooqgen.catmarepository.tables.Propertyvalue;
import de.catma.repository.db.jooqgen.catmarepository.tables.Role;
import de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission;
import de.catma.repository.db.jooqgen.catmarepository.tables.Sourcedocument;
import de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupattribute;
import de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupinstance;
import de.catma.repository.db.jooqgen.catmarepository.tables.Tagdefinition;
import de.catma.repository.db.jooqgen.catmarepository.tables.Taginstance;
import de.catma.repository.db.jooqgen.catmarepository.tables.Taglibrary;
import de.catma.repository.db.jooqgen.catmarepository.tables.Tagreference;
import de.catma.repository.db.jooqgen.catmarepository.tables.Tagsetdefinition;
import de.catma.repository.db.jooqgen.catmarepository.tables.UnseparableCharsequence;
import de.catma.repository.db.jooqgen.catmarepository.tables.User;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserCorpus;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserRole;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserSourcedocument;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserStaticmarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserUsermarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserdefinedSeparatingcharacter;
import de.catma.repository.db.jooqgen.catmarepository.tables.Usermarkupcollection;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Catmarepository extends SchemaImpl {

	private static final long serialVersionUID = 1141049593;

	/**
	 * The reference instance of <code>catmarepository</code>
	 */
	public static final Catmarepository CATMAREPOSITORY = new Catmarepository();

	/**
	 * No further instances allowed
	 */
	private Catmarepository() {
		super("catmarepository");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Corpus.CORPUS,
			CorpusSourcedocument.CORPUS_SOURCEDOCUMENT,
			CorpusStaticmarkupcollection.CORPUS_STATICMARKUPCOLLECTION,
			CorpusUsermarkupcollection.CORPUS_USERMARKUPCOLLECTION,
			MaintenanceSem.MAINTENANCE_SEM,
			Permission.PERMISSION,
			Property.PROPERTY,
			Propertydefinition.PROPERTYDEFINITION,
			PropertydefPossiblevalue.PROPERTYDEF_POSSIBLEVALUE,
			Propertyvalue.PROPERTYVALUE,
			Role.ROLE,
			RolePermission.ROLE_PERMISSION,
			Sourcedocument.SOURCEDOCUMENT,
			Staticmarkupattribute.STATICMARKUPATTRIBUTE,
			Staticmarkupcollection.STATICMARKUPCOLLECTION,
			Staticmarkupinstance.STATICMARKUPINSTANCE,
			Tagdefinition.TAGDEFINITION,
			Taginstance.TAGINSTANCE,
			Taglibrary.TAGLIBRARY,
			Tagreference.TAGREFERENCE,
			Tagsetdefinition.TAGSETDEFINITION,
			UnseparableCharsequence.UNSEPARABLE_CHARSEQUENCE,
			User.USER,
			UserdefinedSeparatingcharacter.USERDEFINED_SEPARATINGCHARACTER,
			Usermarkupcollection.USERMARKUPCOLLECTION,
			UserCorpus.USER_CORPUS,
			UserRole.USER_ROLE,
			UserSourcedocument.USER_SOURCEDOCUMENT,
			UserStaticmarkupcollection.USER_STATICMARKUPCOLLECTION,
			UserTaglibrary.USER_TAGLIBRARY,
			UserUsermarkupcollection.USER_USERMARKUPCOLLECTION);
	}
}
