/**
 * This class is generated by jOOQ
 */
package de.catma.repository.db.jooqgen.catmarepository;


import de.catma.repository.db.jooqgen.catmarepository.tables.Corpus;
import de.catma.repository.db.jooqgen.catmarepository.tables.CorpusSourcedocument;
import de.catma.repository.db.jooqgen.catmarepository.tables.CorpusStaticmarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.CorpusUsermarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem;
import de.catma.repository.db.jooqgen.catmarepository.tables.Permission;
import de.catma.repository.db.jooqgen.catmarepository.tables.Property;
import de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue;
import de.catma.repository.db.jooqgen.catmarepository.tables.Propertydefinition;
import de.catma.repository.db.jooqgen.catmarepository.tables.Propertyvalue;
import de.catma.repository.db.jooqgen.catmarepository.tables.Role;
import de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission;
import de.catma.repository.db.jooqgen.catmarepository.tables.Sourcedocument;
import de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupattribute;
import de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupinstance;
import de.catma.repository.db.jooqgen.catmarepository.tables.Tagdefinition;
import de.catma.repository.db.jooqgen.catmarepository.tables.Taginstance;
import de.catma.repository.db.jooqgen.catmarepository.tables.Taglibrary;
import de.catma.repository.db.jooqgen.catmarepository.tables.Tagreference;
import de.catma.repository.db.jooqgen.catmarepository.tables.Tagsetdefinition;
import de.catma.repository.db.jooqgen.catmarepository.tables.UnseparableCharsequence;
import de.catma.repository.db.jooqgen.catmarepository.tables.User;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserCorpus;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserRole;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserSourcedocument;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserStaticmarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserUsermarkupcollection;
import de.catma.repository.db.jooqgen.catmarepository.tables.UserdefinedSeparatingcharacter;
import de.catma.repository.db.jooqgen.catmarepository.tables.Usermarkupcollection;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in catmarepository
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table catmarepository.corpus
	 */
	public static final Corpus CORPUS = de.catma.repository.db.jooqgen.catmarepository.tables.Corpus.CORPUS;

	/**
	 * The table catmarepository.corpus_sourcedocument
	 */
	public static final CorpusSourcedocument CORPUS_SOURCEDOCUMENT = de.catma.repository.db.jooqgen.catmarepository.tables.CorpusSourcedocument.CORPUS_SOURCEDOCUMENT;

	/**
	 * The table catmarepository.corpus_staticmarkupcollection
	 */
	public static final CorpusStaticmarkupcollection CORPUS_STATICMARKUPCOLLECTION = de.catma.repository.db.jooqgen.catmarepository.tables.CorpusStaticmarkupcollection.CORPUS_STATICMARKUPCOLLECTION;

	/**
	 * The table catmarepository.corpus_usermarkupcollection
	 */
	public static final CorpusUsermarkupcollection CORPUS_USERMARKUPCOLLECTION = de.catma.repository.db.jooqgen.catmarepository.tables.CorpusUsermarkupcollection.CORPUS_USERMARKUPCOLLECTION;

	/**
	 * The table catmarepository.maintenance_sem
	 */
	public static final MaintenanceSem MAINTENANCE_SEM = de.catma.repository.db.jooqgen.catmarepository.tables.MaintenanceSem.MAINTENANCE_SEM;

	/**
	 * The table catmarepository.permission
	 */
	public static final Permission PERMISSION = de.catma.repository.db.jooqgen.catmarepository.tables.Permission.PERMISSION;

	/**
	 * The table catmarepository.property
	 */
	public static final Property PROPERTY = de.catma.repository.db.jooqgen.catmarepository.tables.Property.PROPERTY;

	/**
	 * The table catmarepository.propertydefinition
	 */
	public static final Propertydefinition PROPERTYDEFINITION = de.catma.repository.db.jooqgen.catmarepository.tables.Propertydefinition.PROPERTYDEFINITION;

	/**
	 * The table catmarepository.propertydef_possiblevalue
	 */
	public static final PropertydefPossiblevalue PROPERTYDEF_POSSIBLEVALUE = de.catma.repository.db.jooqgen.catmarepository.tables.PropertydefPossiblevalue.PROPERTYDEF_POSSIBLEVALUE;

	/**
	 * The table catmarepository.propertyvalue
	 */
	public static final Propertyvalue PROPERTYVALUE = de.catma.repository.db.jooqgen.catmarepository.tables.Propertyvalue.PROPERTYVALUE;

	/**
	 * The table catmarepository.role
	 */
	public static final Role ROLE = de.catma.repository.db.jooqgen.catmarepository.tables.Role.ROLE;

	/**
	 * The table catmarepository.role_permission
	 */
	public static final RolePermission ROLE_PERMISSION = de.catma.repository.db.jooqgen.catmarepository.tables.RolePermission.ROLE_PERMISSION;

	/**
	 * The table catmarepository.sourcedocument
	 */
	public static final Sourcedocument SOURCEDOCUMENT = de.catma.repository.db.jooqgen.catmarepository.tables.Sourcedocument.SOURCEDOCUMENT;

	/**
	 * The table catmarepository.staticmarkupattribute
	 */
	public static final Staticmarkupattribute STATICMARKUPATTRIBUTE = de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupattribute.STATICMARKUPATTRIBUTE;

	/**
	 * The table catmarepository.staticmarkupcollection
	 */
	public static final Staticmarkupcollection STATICMARKUPCOLLECTION = de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupcollection.STATICMARKUPCOLLECTION;

	/**
	 * The table catmarepository.staticmarkupinstance
	 */
	public static final Staticmarkupinstance STATICMARKUPINSTANCE = de.catma.repository.db.jooqgen.catmarepository.tables.Staticmarkupinstance.STATICMARKUPINSTANCE;

	/**
	 * The table catmarepository.tagdefinition
	 */
	public static final Tagdefinition TAGDEFINITION = de.catma.repository.db.jooqgen.catmarepository.tables.Tagdefinition.TAGDEFINITION;

	/**
	 * The table catmarepository.taginstance
	 */
	public static final Taginstance TAGINSTANCE = de.catma.repository.db.jooqgen.catmarepository.tables.Taginstance.TAGINSTANCE;

	/**
	 * The table catmarepository.taglibrary
	 */
	public static final Taglibrary TAGLIBRARY = de.catma.repository.db.jooqgen.catmarepository.tables.Taglibrary.TAGLIBRARY;

	/**
	 * The table catmarepository.tagreference
	 */
	public static final Tagreference TAGREFERENCE = de.catma.repository.db.jooqgen.catmarepository.tables.Tagreference.TAGREFERENCE;

	/**
	 * The table catmarepository.tagsetdefinition
	 */
	public static final Tagsetdefinition TAGSETDEFINITION = de.catma.repository.db.jooqgen.catmarepository.tables.Tagsetdefinition.TAGSETDEFINITION;

	/**
	 * The table catmarepository.unseparable_charsequence
	 */
	public static final UnseparableCharsequence UNSEPARABLE_CHARSEQUENCE = de.catma.repository.db.jooqgen.catmarepository.tables.UnseparableCharsequence.UNSEPARABLE_CHARSEQUENCE;

	/**
	 * The table catmarepository.user
	 */
	public static final User USER = de.catma.repository.db.jooqgen.catmarepository.tables.User.USER;

	/**
	 * The table catmarepository.userdefined_separatingcharacter
	 */
	public static final UserdefinedSeparatingcharacter USERDEFINED_SEPARATINGCHARACTER = de.catma.repository.db.jooqgen.catmarepository.tables.UserdefinedSeparatingcharacter.USERDEFINED_SEPARATINGCHARACTER;

	/**
	 * The table catmarepository.usermarkupcollection
	 */
	public static final Usermarkupcollection USERMARKUPCOLLECTION = de.catma.repository.db.jooqgen.catmarepository.tables.Usermarkupcollection.USERMARKUPCOLLECTION;

	/**
	 * The table catmarepository.user_corpus
	 */
	public static final UserCorpus USER_CORPUS = de.catma.repository.db.jooqgen.catmarepository.tables.UserCorpus.USER_CORPUS;

	/**
	 * The table catmarepository.user_role
	 */
	public static final UserRole USER_ROLE = de.catma.repository.db.jooqgen.catmarepository.tables.UserRole.USER_ROLE;

	/**
	 * The table catmarepository.user_sourcedocument
	 */
	public static final UserSourcedocument USER_SOURCEDOCUMENT = de.catma.repository.db.jooqgen.catmarepository.tables.UserSourcedocument.USER_SOURCEDOCUMENT;

	/**
	 * The table catmarepository.user_staticmarkupcollection
	 */
	public static final UserStaticmarkupcollection USER_STATICMARKUPCOLLECTION = de.catma.repository.db.jooqgen.catmarepository.tables.UserStaticmarkupcollection.USER_STATICMARKUPCOLLECTION;

	/**
	 * The table catmarepository.user_taglibrary
	 */
	public static final UserTaglibrary USER_TAGLIBRARY = de.catma.repository.db.jooqgen.catmarepository.tables.UserTaglibrary.USER_TAGLIBRARY;

	/**
	 * The table catmarepository.user_usermarkupcollection
	 */
	public static final UserUsermarkupcollection USER_USERMARKUPCOLLECTION = de.catma.repository.db.jooqgen.catmarepository.tables.UserUsermarkupcollection.USER_USERMARKUPCOLLECTION;
}
