package de.catma.indexer.db;

// Generated 04.05.2012 21:11:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "CatmaIndex")
public class Position implements java.io.Serializable {

	private Integer positionId;
	private int termId;
	private int characterStart;
	private int characterEnd;
	private int tokenOffset;

	public Position() {
	}

	public Position(int termId, int characterStart,
			int characterEnd, int tokenOffset) {
		this.termId = termId;
		this.characterStart = characterStart;
		this.characterEnd = characterEnd;
		this.tokenOffset = tokenOffset;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "positionID", unique = true, nullable = false)
	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	@Column(name = "termID", nullable = false)
	public int getTermId() {
		return this.termId;
	}

	public void setTermId(int termId) {
		this.termId = termId;
	}

	@Column(name = "characterStart", nullable = false)
	public int getCharacterStart() {
		return this.characterStart;
	}

	public void setCharacterStart(int characterStart) {
		this.characterStart = characterStart;
	}

	@Column(name = "characterEnd", nullable = false)
	public int getCharacterEnd() {
		return this.characterEnd;
	}

	public void setCharacterEnd(int characterEnd) {
		this.characterEnd = characterEnd;
	}

	@Column(name = "tokenOffset", nullable = false)
	public int getTokenOffset() {
		return this.tokenOffset;
	}

	public void setTokenOffset(int tokenOffset) {
		this.tokenOffset = tokenOffset;
	}

}
