package de.catma.indexer.db;

// Generated 04.05.2012 21:11:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Term generated by hbm2java
 */
@Entity
@Table(name = "term", catalog = "CatmaIndex")
public class Term implements java.io.Serializable {

	private Integer termId;
	private String documentId;
	private int frequency;
	private String term;

	public Term() {
	}

	public Term(String documentId, int frequency, String term) {
		this.documentId = documentId;
		this.frequency = frequency;
		this.term = term;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "termID", unique = true, nullable = false)
	public Integer getTermId() {
		return this.termId;
	}

	public void setTermId(Integer termId) {
		this.termId = termId;
	}

	@Column(name = "documentID", nullable = false, length = 300)
	public String getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	@Column(name = "frequency", nullable = false)
	public int getFrequency() {
		return this.frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

	@Column(name = "term", nullable = false, length = 300)
	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

}
